### PR TITLE
Add path changes to allow AppImage build to run

### LINKED ISSUE #1504: Attempting AppImage build, error finding files
Hydrogen version *          :  81c1ffaae840e4d68d6b25c011ae2cee674b4ec7
Operating system + version  :  Debian 11 + Docker (podman)
Audio driver + version      :  N/A

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I've been working through packaging Hydrogen as an AppImage, with some success, [project may be found here](
https://github.com/coyote240/hydrogen-build).

AppImage builds successfully, but fails to run, erroring at the `Filesystem::check_permissions` step. Mounting the image I see that the necessary files are present in the archive, but the application is looking in the wrong place.

I've been fishing thru code, but haven't found where I can instruct the application to look to `<imgpath>/usr/share/` instead of `<imgpath>/usr/bin/data`.

I realize this may be considered unsupported, but I'd happily donate my work once I get over these hurdles.

```bash
Copyright 2002-2008 Alessandro Cominu
Copyright 2008-2022 The hydrogen development team
Hydrogen comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it under certain conditions. See the file COPYING for details.
Error: can't open log file for writing...
(E) Filesystem::check_permissions /usr/share/hydrogen/data/ is not a directory
(E) Filesystem::bootstrap will use local data path : /tmp/.mount_HydrogXmpSGo/usr/bin/data/
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/ is not a directory
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/click.wav is not a file
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/demo_songs/ is not a directory
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/drumkits/ is not a directory
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/emptySample.wav is not a file
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/hydrogen.default.conf is not a file
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/i18n/ is not a directory
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/img/ is not a directory
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/themes/ is not a directory
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/xsd/ is not a directory
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/xsd/drumkit_pattern.xsd is not a file
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/xsd/drumkit.xsd is not a file
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/xsd/playlist.xsd is not a file
(E) Filesystem::check_permissions /home/signal9/.hydrogen/data/emptySong.h2song is not a file
(E) Filesystem::check_permissions /tmp/.mount_HydrogXmpSGo/usr/bin/data/hydrogen.default.conf is not a file
(E) Filesystem::check_permissions /home/signal9/.hydrogen/hydrogen.conf is not a file
(E) ::void handleFatalSignal(int) Fatal signal 11
(E) ::void handleFatalSignal(int) out/Hydrogen-efd25a37-x86_64.AppImage(+0x214ed6) [0x561358954ed6]
(E) ::void handleFatalSignal(int) /lib/x86_64-linux-gnu/libc.so.6(+0x3bd60) [0x7f682ba5bd60]
(E) ::void handleFatalSignal(int) /tmp/.mount_HydrogXmpSGo/usr/bin/../lib/libQt5Gui.so.5(_ZNK6QColor3redEv+0x18) [0x7f682c7b7d18]
(E) ::void handleFatalSignal(int) out/Hydrogen-efd25a37-x86_64.AppImage(+0x315727) [0x561358a55727]
(E) ::void handleFatalSignal(int) out/Hydrogen-efd25a37-x86_64.AppImage(+0x363cf4) [0x561358aa3cf4]
(E) ::void handleFatalSignal(int) out/Hydrogen-efd25a37-x86_64.AppImage(+0x35b0fe) [0x561358a9b0fe]
(E) ::void handleFatalSignal(int) out/Hydrogen-efd25a37-x86_64.AppImage(+0x3512d4) [0x561358a912d4]
(E) ::void handleFatalSignal(int) out/Hydrogen-efd25a37-x86_64.AppImage(+0x34fe4d) [0x561358a8fe4d]
(E) ::void handleFatalSignal(int) out/Hydrogen-efd25a37-x86_64.AppImage(main+0x168d) [0x561358956c87]
(E) ::void handleFatalSignal(int) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7f682ba46d0a]
(E) ::void handleFatalSignal(int) out/Hydrogen-efd25a37-x86_64.AppImage(+0x6457a) [0x5613587a457a]
Segmentation fault
```

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

### PR DESCRIPTION
**Pull request by coyote240**
Fixes #1504 

Minor changes to ifdefs and cmake config to direct portable build to find data files.

replaces #1517

### CODE REVIEW

**Comment by theGreatWhiteShark** [comment]
Hey @coyote240 ,

Thanks again!

You probably managed to build an AppImage of Hydrogen locally, right? How about we add an option to build one to our [build.sh](https://github.com/hydrogen-music/hydrogen/blob/master/build.sh) script to help others to do the same. If you are not familiar with bash programming, you could also just copy&paste the commands you used in here and I'll add it.

As I understand AppImage to be a portable executable supported by a wide variety of Linux distributions (right?) our goal in the long run should be to add it to our build pipeline and provide it along with the other release artifacts. But don't worry, that's future work :wink:

**Comment by coyote240** [comment]
@theGreatWhiteShark 

I've actually got an automated docker build, found [here](https://github.com/coyote240/hydrogen-build). Let me see what I can do about nudging it into `build.sh`. I do a fair amount w/ build pipelines, I may be able to help get into hydrogen's build pipeline as well.

**Comment by cme** [comment]
Awesome :) What else do we need to do to build the actual AppImage? I guess cmake is run with the prefix pointing to where the `AppDir` will be, and then `appimagetool` pointed at that? Since it looks like `appimagetool` comes as an appimage it should be easy to acquire into the Appveyor build flow :)

**Comment by coyote240** [comment]
@cme That's pretty much it. I'll integrate my changes into `build.sh`, then getting `appimagetool` into your pipeline is the only missing piece.

I'll update my Dockerfile to build using the project's build script and see where I get.

Should that be part of this PR, or in another?

**Comment by theGreatWhiteShark** [comment]
> Should that be part of this PR, or in another?

As you wish.

**Pull request closed without merging**
