### PR TITLE
refactor Song class

### PR DESCRIPTION
**Pull request by theGreatWhiteShark**
- adopt naming convention
- make member variables private and use setter and getters
- review constness

At first I just wanted to introduce a setter for the bpm member of the `Song`. But things went out of hand.

### CODE REVIEW

**Comment by cme** [comment]
Ace. How much of this was automated / repeatable? Because I just realised anything I am likely to commit soon will cause conflicts with this, so merging this sooner would be better and reduce conflicts.

(I had a quick look through, looks good!)

> At first I just wanted to introduce a setter for the bpm member of the `Song`. But things went out of hand.

I know that feeling... :D

**Comment by jeremyz** [comment]
All of this because I can't stand neither camelCase nor member variable prefixes, sorry ;)

**Comment by theGreatWhiteShark** [comment]
> How much of this was automated / repeatable?

Let's say there was enough automation for the whole thing to only take a whole evening. What mauser is doing in #1008 is on another scale. (Admittedly, I started that one once too. But gave halfway through :smile: )

**Comment by theGreatWhiteShark** [comment]
> All of this because I can't stand neither camelCase nor member variable prefixes, sorry ;)

Well, it's not my favorite either. But the inconsistency gives an almost physical pain if looking at it for too long. :wink:

**Pull request merged**
