### PR TITLE
Warn user of missing samples on song load

### PR DESCRIPTION
**Pull request by cme**
Make the GUI warn users of missing samples when loading songs
  * Refactor HydrogenApp's use of InfoBar to allow multiple InfoBars
  * Present an InfoBar on missing samples, with a button offering to open drumkits

This addresses #902.

### CODE REVIEW

**Comment by mauser** [comment]
Hi Colin! 

what about storing the "missing samples" information for an instrument (iso. storing it per song)? It would feel more "natural" (?) to me to have an indicator which tells me "Hey, there is something wrong with that Kick drum instrument here.." . The user could then  decide himself if this is a problem or not. Maybe there could also be a small yellow warning sign (those triangular things with an exclamation mark..) at the beginning of the instrument name in the pattern editor. Maybe a missing sample is ok if you know that the instrument is not important (maybe the third bottom snare sample your friend added..), but irt a t could be fatal if this is your primary kick drum or whatever..

Just a thought to start a discussion, i'm not wanting to say that this has to implemented exactly in this way to get accepted :)

**Comment by cme** [comment]
I like this idea. I think the infobar notification ought to be kept, though, as it's useful in what might be the most common case.

Also, a tooltip with list of missing samples on hovering over the indicator might be useful.

**Comment by cme** [comment]
Updated to flag individual instruments as degraded, with little warning triangle, with tooltip and an error box. 

image

**Comment by trebmuh** [comment]
Just throwing an idea in the dark here (I don't know if it's already in the code or not).
As a user, I'd like to have a bit of an explanation while mouse-hovering the "yellow attention triangle" to understand why it is here.

HTH

**Comment by cme** [comment]
> Just throwing an idea in the dark here (I don't know if it's already in the code or not).
> As a user, I'd like to have a bit of an explanation while mouse-hovering the "yellow attention triangle" to understand why it is here.

I agree. It's already there:

image

Open to suggestions on wording etc.

**Comment by trebmuh** [comment]
Nice!

**Comment by mauser** [comment]
Thanks a lot, merged!

**Pull request merged**
