### PR TITLE
Menu redesign

### PR DESCRIPTION
**Pull request by blablack**
Here is the pull request for the menu redesign.
It is most definitely not the definitive version and I would like to use this space for comments and feedbacks.

screenshot from 2015-11-03 19-58-17

The banks menu entry:
- New: Equivalent to "Clear All" at the moment
- Open: To open a System or User drumkits (at the moment available only in the Sound Library)
- Properties: Display the drumkit library (at the moment available only in the Sound Library)
- Save: Save the currently open drumkit
- Save As: Save with a new name to be displayed in the User drumkits
- Export: Current export functionalities
- Import: the current "Import -> Local File"
- Online import: the current "Import -> Internet"

In the instruments menu entry is left:
- Add Instrument
- Clear All
- Add Component: to add a component (at the moment available only in the Sound Library)

I tried to make as little modification on other parts of Hyrogen and I reused the existing form "as-is" and focused only on the menu changes:
- Import and Online import call the same form - the different is that they pre-select the tab.
- I noticed that being able to undo adding a component is not done - I created this ticket regarding this https://github.com/hydrogen-music/hydrogen/issues/329

### CODE REVIEW

**Comment by trebmuh** [comment]
@blablack : I've been trying to build the current GIT (https://github.com/hydrogen-music/hydrogen/commit/d7dacfedf73ede1af24ddedf260cfce5ca77df18) with this patch, but unfortunately, when trying to patch, I've got those errors:
```
patching file src/gui/src/MainForm.cpp
Hunk #1 succeeded at 61 (offset 3 lines).
Hunk #2 succeeded at 297 (offset 4 lines).
Hunk #3 FAILED at 1717.
1 out of 3 hunks FAILED
patching file src/gui/src/MainForm.h
Hunk #1 succeeded at 88 (offset 2 lines).
patching file src/gui/src/InstrumentRack.cpp
patching file src/gui/src/MainForm.cpp
Hunk #1 succeeded at 60 (offset 3 lines).
Hunk #2 succeeded at 301 (offset 4 lines).
Hunk #3 succeeded at 868 (offset 10 lines).
patching file src/gui/src/MainForm.h
Hunk #1 succeeded at 89 (offset 2 lines).
patching file src/gui/src/SoundLibrary/SoundLibraryOpenDialog.cpp
patching file src/gui/src/SoundLibrary/SoundLibraryOpenDialog.h
patching file src/gui/src/SoundLibrary/SoundLibraryPanel.cpp
patching file src/gui/src/SoundLibrary/SoundLibraryPanel.h
patching file src/gui/src/MainForm.cpp
Hunk #1 succeeded at 306 (offset 4 lines).
Hunk #2 succeeded at 949 (offset 10 lines).
patching file src/gui/src/MainForm.h
Hunk #1 succeeded at 85 (offset 2 lines).
patching file src/gui/src/MainForm.cpp
Hunk #1 succeeded at 312 (offset 4 lines).
Hunk #2 succeeded at 944 (offset 10 lines).
Hunk #3 succeeded at 1001 (offset 10 lines).
patching file src/gui/src/MainForm.h
Hunk #1 succeeded at 88 (offset 2 lines).
patching file src/gui/src/SoundLibrary/SoundLibraryImportDialog.cpp
patching file src/gui/src/SoundLibrary/SoundLibraryImportDialog.h
Hunk #1 FAILED at 37.
1 out of 1 hunk FAILED
patching file src/gui/src/MainForm.cpp
Hunk #1 succeeded at 1002 (offset 10 lines).
patching file src/gui/src/InstrumentEditor/InstrumentEditor.h
Hunk #1 succeeded at 66 (offset 1 line).
Hunk #2 succeeded at 192 (offset 11 lines).
patching file src/gui/src/MainForm.cpp
Hunk #1 FAILED at 33.
Hunk #2 succeeded at 325 (offset 4 lines).
Hunk #3 succeeded at 868 (offset 10 lines).
1 out of 3 hunks FAILED
patching file src/gui/src/MainForm.h
Hunk #1 succeeded at 89 (offset 2 lines).
```
...which I found a bit strange since it's written that "This branch has no conflicts with the base branch" in here. o_O
Any advise/help would be appreciated.

**Comment by blablack** [comment]
@trebmuh I just synced the branch with master - this should help I hope!

**Comment by trebmuh** [comment]
@blablack: I tried to rebuild it.

1. git clone https://github.com/blablack/hydrogen.git
2. cd hydrogen
3. git checkout menu_redesign 

Then, when building within a pbuilder environment, I've got the following:
```
[ 60%] Building CXX object src/gui/CMakeFiles/hydrogen.dir/src/MainForm.cpp.o
cd /tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/obj-x86_64-linux-gnu/src/gui && /usr/bin/g++    -O2 -std=gnu++11 -Wno-deprecated-register -fno-implement-inlines -g  -I/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/obj-x86_64-linux-gnu/src/gui -I/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/gui/src -I/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/core/include -I/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/obj-x86_64-linux-gnu/src/core/include -I/usr/include/qt4/QtDesigner -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4/QtScriptTools -I/usr/include/qt4/QtDBus -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtHelp -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtTest -I/usr/include/qt4/QtScript -I/usr/include/qt4/QtSvg -I/usr/include/qt4/Qt3Support -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore -I/usr/share/qt4/mkspecs/default -I/usr/include/qt4    -o CMakeFiles/hydrogen.dir/src/MainForm.cpp.o -c /tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/gui/src/MainForm.cpp
src/gui/CMakeFiles/hydrogen.dir/build.make:968: recipe for target 'src/gui/CMakeFiles/hydrogen.dir/src/MainForm.cpp.o' failed
```

The log says:
```
/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/gui/src/MainForm.cpp: In member function 'void MainForm::action_instruments_saveLibrary()':
/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/gui/src/MainForm.cpp:1026:15: error: no matching function for call to 'H2Core::Drumkit::save(QString, QString, QString, QString, H2Core::InstrumentList*, std::vector<H2Core::DrumkitComponent*>*, bool)'
          true ) ) {
               ^
/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/gui/src/MainForm.cpp:1026:15: note: candidates are:
In file included from /tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/core/include/hydrogen/hydrogen.h:35:0,
                 from /tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/gui/src/MainForm.cpp:26:
/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/core/include/hydrogen/basics/drumkit.h:89:8: note: bool H2Core::Drumkit::save(bool)
   bool save( bool overwrite=false );
        ^
/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/core/include/hydrogen/basics/drumkit.h:89:8: note:   candidate expects 1 argument, 7 provided
/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/core/include/hydrogen/basics/drumkit.h:97:8: note: bool H2Core::Drumkit::save(const QString&, bool)
   bool save( const QString& dk_dir, bool overwrite=false );
        ^
/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/core/include/hydrogen/basics/drumkit.h:97:8: note:   candidate expects 2 arguments, 7 provided
/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/core/include/hydrogen/basics/drumkit.h:132:15: note: static bool H2Core::Drumkit::save(const QString&, const QString&, const QString&, const QString&, const QString&, const QString&, H2Core::InstrumentList*, std::vector<H2Core::DrumkitComponent*>*, bool)
   static bool save( const QString& name, const QString& author, const QString& info, const QString& license, const QString& image, const QString& imageLicense, InstrumentList* instruments, std::vector<DrumkitComponent*>* components, bool overwrite=false );
               ^
/tmp/buildd/hydrogen-menuredesign-0.9.7-beta2+20160811-git8b24339/src/core/include/hydrogen/basics/drumkit.h:132:15: note:   candidate expects 9 arguments, 7 provided
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register"
```

Hope that can help.

**Comment by blablack** [comment]
@trebmuh this should be fixed now

**Comment by trebmuh** [comment]
@blablack : I can confirmed it is fixed since it built here.
I've been trying it, and so far, it looks fine to me. Nice job !

**Comment by trebmuh** [comment]
@blablack : could you enjoy this menu redesign work to add this : https://github.com/hydrogen-music/hydrogen/issues/11 ?

**Comment by mauser** [comment]
Hi everyone! 

I've merged this pull request now.. The only change i've made was renaming the "Banks" menu to "Drumkits". We've also used the term "SoundLibrary" for that in the past, but it seems to be the case that most people just stay with "Drumkit".

**Comment by trebmuh** [comment]
Sweet.

**Comment by trebmuh** [comment]
I did rebuild git from https://github.com/hydrogen-music/hydrogen/commit/b19ba20489588e4b40031235ecd3157610760a85 and updated the translation, and it looks to be fine.  Thanks @blablack and @mauser !

**Comment by mauser** [comment]
A word about the translation updates: It is very likely that a lot of those strings will change again and stuffs gets often renamed or added at the moment, so it might be worth to wait until the first beta with translations.

**Comment by trebmuh** [comment]
@mauser thanks for pointing that out to me.

**Pull request merged**
