### PR TITLE
Probability Engine

### PR DESCRIPTION
**Pull request by elpescado**
# Overview

This feature allows to assign a probability value to each note. That value specifies probability that particular note will be played. Value 1.0 means that note will be played every time. Lowering that value will lower chances that note will be played, down to 0 which means that note will never be played.

This allows to create more complex and less predictable songs using less patterns.

screenshot
[Audio demo](https://soundcloud.com/el-pescado/hydrogen-probability-engine/s-xceyY): eight bars consisting of just one pattern.
# Features
- Probability panel editor
- Player support
- Audio export
- Midi export
- Song loading/saving
- Undo/redo
# Regressions

This branch should be backwards compatible. When note has no probability set, default value of 1.0 is used, which means note will always be played, preserving expected behavior.

### CODE REVIEW

**Comment by trebmuh** [comment]
Sounds promising as well !

**Comment by blablack** [comment]
That's a really cool functionality!

**Comment by trebmuh** [comment]
Same here than in https://github.com/hydrogen-music/hydrogen/pull/356#issuecomment-189964353 @elpescado 

I've been trying to build hydrogen from a fresh git clone (  https://github.com/hydrogen-music/hydrogen/commit/956fd11414815318aa4a0d7379ff1d368dc31d0b ) with the addition of the you patch : https://patch-diff.githubusercontent.com/raw/hydrogen-music/hydrogen/pull/358.patch
but it fails building.
What would be your suggestion?

**Comment by elpescado** [comment]
What errors are you getting?

One thing I can think of is that this branch requires C++11 support from compiler. I created pull request which enables it, but it hasn't been merged yet.

**Comment by Nat-Napoletano** [comment]
I may be a little late to the game, but wouldn't this feature be better if it were coupled with a more general random variance in MIDI note velocity. This would be a more natural simulation of a human player who may deliver some "ghost" notes and undershoot the velocity or miss the drum making some hits inaudible. So I'm advocating for random velocity within a programmable range and a probability value to each note simulating a conscious decision to play  a different pattern.

**Comment by elpescado** [comment]
Any feedback?

**Comment by trebmuh** [comment]
Hi @elpescado : trying to build hydrogen from today (https://github.com/hydrogen-music/hydrogen/commit/d7dacfedf73ede1af24ddedf260cfce5ca77df18) + your patch: https://patch-diff.githubusercontent.com/raw/hydrogen-music/hydrogen/pull/358.patch

I've got the following:
'''patching file src/core/include/hydrogen/basics/note.h
Hunk #1 FAILED at 192.
Hunk #2 succeeded at 305 (offset 9 lines).
Hunk #3 FAILED at 417.
2 out of 3 hunks FAILED
patching file src/core/src/basics/note.cpp
Hunk #1 succeeded at 62 (offset 1 line).
Hunk #2 succeeded at 109 (offset 8 lines).
patching file src/core/src/hydrogen.cpp
Hunk #1 succeeded at 485 (offset -2 lines).
patching file src/gui/src/PatternEditor/NotePropertiesRuler.cpp
Hunk #2 FAILED at 193.
1 out of 6 hunks FAILED
patching file src/gui/src/PatternEditor/NotePropertiesRuler.h
patching file src/gui/src/PatternEditor/PatternEditorPanel.cpp
patching file src/gui/src/PatternEditor/PatternEditorPanel.h
Hunk #1 FAILED at 65.
Hunk #2 FAILED at 155.
2 out of 2 hunks FAILED
patching file src/core/src/basics/note.cpp
Hunk #1 succeeded at 222 (offset 14 lines).
Hunk #2 succeeded at 241 (offset 14 lines).
patching file src/tests/note_test.cpp
patching file data/xsd/drumkit_pattern.xsd
patching file src/core/src/basics/song.cpp
Hunk #1 succeeded at 1041 (offset -4 lines).
Hunk #2 succeeded at 1064 (offset -4 lines).
patching file src/core/src/local_file_mgr.cpp
Hunk #7 succeeded at 1449 (offset 30 lines).
patching file src/gui/src/PatternEditor/DrumPatternEditor.cpp
patching file src/gui/src/PatternEditor/DrumPatternEditor.h
patching file src/gui/src/PatternEditor/NotePropertiesRuler.cpp
Hunk #1 succeeded at 473 (offset -12 lines).
patching file src/gui/src/UndoActions.h
patching file src/core/src/smf/smf.cpp'''

Also, note that github is telling here that "This branch has conflicts that must be resolved".
I'd like to help testing this feature which looks definitely to be a great addition to Hydrogen from my POV.

Hope that helps

**Comment by elpescado** [comment]
I have to merge latest master, unfortunately I'm bit busy right now. In the meantime, you could just checkout my branch directly.

**Comment by mauser** [comment]
@elpescado: At the moment i think that this (and your automation pull request) will be too much for 0.9.7, but both are very nice features! My plan is to get a beta3 out in the next days (along with the feature freeze for 0.9.7) and create the rc1 in two or three weeks. Both features would be the first things to merge in 0.9.8 for me (well, after testing :smile: ).

**Comment by trebmuh** [comment]
@elpescado: I've been building from your branch, and fiddling around that I love it, really great addition to hydrogen!
While playing with it, I've seen nothing strange, it does look to play as expected.
Great job here!

**Comment by elpescado** [comment]
I have updated my branch so that it should merge cleanly.

**Comment by IvanDSM** [comment]
Is it updated? This would be a great addition to 0.9.8!

**Comment by mauser** [comment]
Hi @elpescado , 

thanks a lot for the pull request! I've merged the request now, so it will appear in the next version of hydrogen (1.0).

**Comment by trebmuh** [comment]
Sweet !

**Comment by trebmuh** [comment]
I did rebuild git from https://github.com/hydrogen-music/hydrogen/commit/b19ba20489588e4b40031235ecd3157610760a85 2 days ago and have been playing around with this feature which works as expected. So far, I didn't notice anything strange. I really like this feature, thanks @elpescado !

Thanks!

**Comment by oddtime** [comment]
Just tried it on 1.0.0 beta, great idea.

**Pull request merged**
