### PR TITLE
[SampleEditor] volume envelope reading and last point edition (fixes #782)

### LINKED ISSUE #782: H2 crashes when editing the volume envelope in sample editor
Hydrogen version *          : 0d3bb860696c7149cd0eb9f722a9c13751a359c7
Operating system + version  : ubuntu 16.04
Audio driver + version      : jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

open the sample editor for a random iinstrument
select the volume envelope 
click in on the waveform (to draw the envelope)
h2 crashes

```
(I) SongWriter::writeSong Saving song /home/thijs2/Music/hydrogen songs/_BHBM/intracranial_seq_j1.autosave.h2song
(I) SongWriter::writeSong Save was successful.
(I) SongWriter::writeSong Saving song /home/thijs2/Music/hydrogen songs/_BHBM/intracranial_seq_j1.autosave.h2song
(I) SongWriter::writeSong Save was successful.
(W) Sampler::__render_note Velocity did fall into a hole between the instrument layers.
(W) Sampler::__render_note NULL sample for instrument -- EMPTY DUMMY --. Note velocity: 0.628571
(I) SongWriter::writeSong Saving song /home/thijs2/Music/hydrogen songs/_BHBM/intracranial_seq_j1.autosave.h2song
(I) SongWriter::writeSong Save was successful.
(I) SampleEditor::~SampleEditor DESTROY
(I) SampleEditor::SampleEditor INIT

Thread 1 "hydrogen" received signal SIGSEGV, Segmentation fault.
0x0000555555718eee in TargetWaveDisplay::mouseMoveEvent (this=0x555557a3a8c0, 
    ev=0x7fffffffdaf0)
    at /home/thijs2/Music/Hydrogen_Code/hydrogen_31okt2019/src/gui/src/SampleEditor/TargetWaveDisplay.cpp:272
---Type <return> to continue, or q <return> to quit---
272						Frame = m_VelocityEnvelope[i]->frame;

(gdb) bt
#0  0x0000555555718eee in TargetWaveDisplay::mouseMoveEvent(QMouseEvent*) (this=0x555557a3a8c0, ev=0x7fffffffdaf0)
    at /home/thijs2/Music/Hydrogen_Code/hydrogen_31okt2019/src/gui/src/SampleEditor/TargetWaveDisplay.cpp:272
#1  0x00007ffff733a038 in QWidget::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff72fb82c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff730364f in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff5d969a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff7302622 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff735514b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff73577ba in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff72fb82c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff73030f4 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff5d969a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#11 0x00007ffff6358523 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#12 0x00007ffff6359ff5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#13 0x00007ffff63312eb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#14 0x00007fffe773e1c0 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#15 0x00007ffff2160287 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff21604c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff216054c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff5def8ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff5d949ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff5d9da84 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x0000555555781b9d in main(int, char**) (argc=4, argv=0x7fffffffe5b8) at /home/thijs2/Music/Hydrogen_Code/hydrogen_31okt2019/src/gui/src/main.cpp:406

```

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

### PR DESCRIPTION
**Pull request by charbeljc**
* correct volume envelope reading (frame and value where swapped)
* avoid crash when editing last point.

### CODE REVIEW

**Comment by charbeljc** [comment]
Hello Hydrogen devs and users. This PR fixes #782 

Best regards !

**Review by theGreatWhiteShark — APPROVED** [review]
Thanks a lot!

**Comment by theGreatWhiteShark** [comment]
Hey @charbeljc ,

Could you change the target of the PR to the `master` branch? Since it fixes a bug that crashes Hydrogen, it would be nice to integrate it into the upcoming release.

**Comment by charbeljc** [comment]
Hi @theGreatWhiteShark ,

See #1299 for the same PR on master!

**Pull request closed without merging**
