### PR TITLE
Triplet position fix

### PR DESCRIPTION
**Pull request by pvint**
Fix for issue 366 where notes get placed in wrong position when at highest zoom level and placing triplets.

### CODE REVIEW

**Comment by mauser** [comment]
Thanks a lot Paul, tested and merged!!

**Comment by pvint** [comment]
No problem, it was a fun one to figure out!

**Comment by trebmuh** [comment]
please, see https://github.com/hydrogen-music/hydrogen/issues/366

**Comment by trebmuh** [comment]
Well done for the final fix!

**Pull request merged**
