### PR TITLE
Fixes Raptor2 compile issue

### PR DESCRIPTION
**Pull request by pvint**
See issue #342 

I have tested this on several Gentoo installations and on Debian Jessie - all work fine (the gentoo installs failed to compile without this change, Jessie was OK either way).

### CODE REVIEW

**Comment by mauser** [comment]
Hi! 

I'm unsure about this fix..  i'm afraid that this change breaks build which are not using pkgconfig but having the raptor issue described in #194 ? It would also be interesting to see why you have to use the PC_ prefix. Maybe you could have a look at the behaviour of FindHelper.cmake on your system? There are some lines which can be commented out to give more details about the populated variables..  

In addition, i do not really understand why we need that include in the main CMakeLists.txt in the first place , since there is an similar statement in src/core/CMakeLists.txt. I believe that the #194 would be better fixed by including ${LRDF_INCLUDE_DIRS} in CMakeLists.txt.  Could you investigate further in this direction? At the moment i don't have access to a gentoo system or such, so it is hard for me to look deeper into the problem.

**Comment by pvint** [comment]
I will look into it more... to be honest I don't remember anymore how I came up with the PC_ prefix some months ago.... all I know is I need it to make it compile. I now have two systems (one Gentoo and one Debian Jessie) and one needs this fix and one doesn't, so I can test fairly well.

I will test out src/core/CMakeLists.txt - I think you're right in that it's a more appropriate place.

I will also look into FindHelper.cmake.

Thanks @mauser 

Paul

**Comment by pvint** [comment]
I'm glad you questioned this, @mauser as it was good to have a deeper look (and I learned a bit about cmake along the way!).

I have removed the whole if(LRDF_FOUND) bit in CMakelists.txt, and in src/core/CMakelists.txt I simply added "${RAPTOR_INCLUDE_DIRS}" to the includes.

This made more sense, as pkg-config returns the correct include dir on the machine with raptor2 in /usr/nclude/raptor2/raptor.h and on the machines with raptor.h in the default includes dir pkg_config returns nothing, which also works.

On my Gentoo system:
pvint@nautilus /usr/local/src/hydrogen $ pkg-config lrdf --cflags
-I/usr/include/raptor2

Let me know what you think

Paul

**Comment by mauser** [comment]
Great! That looks good. 

@schivmeister : Could you please check if hydrogen still compiles for you? This pull request modified a part of code from your isse #194.

**Comment by trebmuh** [comment]
added to https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-0.9.7#bugfixes

**Comment by schivmeister** [comment]
Hey guys, I don't think I will be able to get to it in a timely manner as I have been away from my Linux systems. However, the proposed changes look like the better solution as mine was just a hack (and does not work for everyone as we can see from the newer bug reports).

**Pull request merged**
