### PR TITLE
Localization Simplified Chinese

### PR DESCRIPTION
**Pull request by guocheng98**
Add Simplified Chinese (zh_CN) localization file into i18n folder

### CODE REVIEW

**Comment by mauser** [comment]
Hi @aaronbcn,

i can see that a lot of strings are marked as "unfinished" in your translation file, but you already added a translation for them. Setting the "finished" flag will make it easier to detect how complete the translation of a specific language is. But this is not a big issue, since it does not affect the translation itself.

**Comment by aaronbcn** [comment]
> Hi @aaronbcn,
> 
> 
> 
> i can see that a lot of strings are marked as "unfinished" in your translation file, but you already added a translation for them. Setting the "finished" flag will make it easier to detect how complete the translation of a specific language is. But this is not a big issue, since it does not affect the translation itself.

I noticed it too. I think it is because I used another localization tool instead of Qt Linguist. When I have done the technical verification, I'll try using Linguist to confirm, which should change all the "untranslated" attributes to "translated".

**Comment by aaronbcn** [comment]
I just updated the zh_CN localization file.

There are some translations that I am not sure about, or I do not know how to translate, which are marked with the attribute _type="unfinished"_ in the _<translation></translation>_ tag. and accompanied by some comments from me. I would appreciate it if anyone could answer these comments.

Besides, I have found certain i18n bugs when doing technical verification. See the file named "i18n bugs" in this comment.
[i18n bugs.docx](https://github.com/hydrogen-music/hydrogen/files/5793156/i18n.bugs.docx)

Lastly, I would also point out a minor style problem of the original text: I would make sure that "MIDI" and "JACK" are always capitalized as they are acronyms.

**Comment by trebmuh** [comment]
@aaronbcn : nice, good job.

About the comment, if you put those in the chinese translation file, it's usually only for reading by people using the same translating tool than you + talking the same language. It's probably better if you put your question here in a message text on github.

About the attached i18n issue doc, you already reported it on #1089 (now closed). It's usually not the best thing to say many time the same thing in different place. Github provide the capacity of linking to another issue/comment/PR/... easily which is much better an manageable. Please use #397 for the i18n issues you found.

**Comment by theGreatWhiteShark** [comment]
@aaronbcn Thanks a lot for your translation!

I took care of your bugs. Could you get the newest code and run the [updateTranslations.sh](https://github.com/hydrogen-music/hydrogen/blob/master/data/i18n/updateTranslations.sh) script after the pull request #1100 got merged into master (probably in a couple of days)?

Regarding your comments:

```xml
<name>AudioEngineInfoForm_UI</name>
<message>
  <source>Form1</source>
  <translatorcomment>What does this string represent? Did not find it in the UI.</translatorcomment>
  <translation type="unfinished">Form1</translation>
</message>
```
Represents nothing. I removed it.

```xml
<message>
  <source>Choose random entry.</source>
  <translatorcomment>Punctuation not needed</translatorcomment>
  <translation>随机选择</translation>
</message>
```
Done

```xml
<message>
  <source>Modus:</source>
  <translatorcomment>方式：</translatorcomment>
  <translation>Modus:</translation>
</message>
```
This one probably got mixed up

```xml
<message>
  <source>Param.</source>
  <translatorcomment>The punctuation used for source text indicates abbr., which is not the case in Chinese.</translatorcomment>
  <translation>参数</translation>
</message>
```
Even better. So, in Chinese the point can be dropped.

```xml
<message>
  <source>destructive mode pre delete settings</source>
  <translatorcomment>What are pre detele settings?</translatorcomment>
  <translation type="unfinished">破坏性模式：预先删除设置</translation>
</message>
```
Hmm. Just discovered this one myself and it's not documented. I will
check.

```xml
<message>
  <source>Jack-Time-Master on/off</source>
  <translatorcomment>What is jack time master?</translatorcomment>
  <translation type="unfinished">打开/关闭主 JACK 时间</translation>
</message>
```
Using the JACK the audio/midi input and output ports of any number of
application can be connected. Using the JACK Timebase Master
functionality one of these programs can broadcast both speed and
measure information to all other connected applications in order to
have a more fine-grained transport control.

```xml
<message>
  <source>Use lash</source>
  <translatorcomment>Not sure about translation. What is lash in this context?</translatorcomment>
  <translation type="unfinished">使用毛刷</translation>
</message>
```
LASH (acronym for LASH Linux Audio Handler) is a protocol allowing for
session management in Linux (recalling songs, preferences, and JACK
port connections).

```xml
<message>
  <source>Meters falloff speed</source>
  <translatorcomment>Not sure about translation. What is falloff speed in this context?</translatorcomment>
  <translation type="unfinished">测量衰减速度</translation>
</message>
```
In case of a rapid sound lasting for just a milli second the meters in
the Mixer would raise to peak value and fall of immediately without
the user being able to see them. The falloff speed introduces a
delay. The smaller the value, the longer the meter requires to reach
0dB again.

**Comment by trebmuh** [comment]
@guocheng98 any news here?

**Comment by guocheng98** [comment]
> @guocheng98 any news here?

I'm working on it, should be done this weekend. Is that okay?

**Comment by trebmuh** [comment]
> I'm working on it, should be done this weekend. Is that okay?

Sure thing.
Alternatively, you can send a PR as it is now and update it later.
The next 1.1 release isn't that far from now, it would be sad if the release would miss your translation.

**Comment by guocheng98** [comment]
I just updated the translation file. Source strings are now aligned with current master base. Right now all translation segments in the hydrogen_zh_CN file have an unfinished attribute due to that I used another localization software other than Linguist. It should not affect compilation and I will correct them later. BTW, I will finish all translation and testing work this weekend and upload the final version. Cheers!

**Comment by theGreatWhiteShark** [comment]
Hey @guocheng98,

don't worry about the "unfinished" attributes. I can remove them in a search-and-replace.

There are a number of messages for which both the source and the translation are identical

``` xml
    <message>
        <source>is a system drumkit and can&apos;t be deleted.</source>
        <translation type="unfinished">is a system drumkit and can&apos;t be deleted.</translation>
    </message>
    <message>
        <source>Not implemented yet.</source>
        <translation type="unfinished">Not implemented yet.</translation>
    </message>
```

is this intended or by accident?

Also, starting with the next release of Hydrogen we offer translators to be listed in the Info > About dialog as active translators with a name/handle and their email address. The idea is to allow people to hint translation issues without the daunting atmosphere when putting them on public display on the dev mailing list or a separate Github issue. But this is purely optional and there is no obligation resulting from your commitment of translating the GUI.

**Comment by guocheng98** [comment]
> Hey @guocheng98,
> 
> don't worry about the "unfinished" attributes. I can remove them in a search-and-replace.
> 
> There are a number of messages for which both the source and the translation are identical
> 
> ```
>     <message>
>         <source>is a system drumkit and can&apos;t be deleted.</source>
>         <translation type="unfinished">is a system drumkit and can&apos;t be deleted.</translation>
>     </message>
>     <message>
>         <source>Not implemented yet.</source>
>         <translation type="unfinished">Not implemented yet.</translation>
>     </message>
> ```
> 
> is this intended or by accident?
> 
> Also, starting with the next release of Hydrogen we offer translators to be listed in the Info > About dialog as active translators with a name/handle and their email address. The idea is to allow people to hint translation issues without the daunting atmosphere when putting them on public display on the dev mailing list or a separate Github issue. But this is purely optional and there is no obligation resulting from your commitment of translating the GUI.

The identical segments are due to the fact that I haven't translated them yet, but I'll  finish off today.

I think the idea of listing translators in the info is excellent. I have no problem with that! :)

**Comment by guocheng98** [comment]
Translation for upcoming release of Hydrogen 1.1 completed. Pls check.

If everything is okay, I will do the technical verification when Hydrogen 1.1 is officially released and see if there is any problem with the localization (truncation, wrong translation due to lack of context, hotkey missing, etc.).

Cheers

**Comment by theGreatWhiteShark** [comment]
> Translation for upcoming release of Hydrogen 1.1 completed. Pls check.

Awesome! Everything looks nice. Thank you very much!

> I think the idea of listing translators in the info is excellent. I have no problem with that! :)

Should I use you outlook.com address you used to send a mail to the hydrogen-devel mailing list or another one?

**Comment by guocheng98** [comment]
> > Translation for upcoming release of Hydrogen 1.1 completed. Pls check.
> 
> 
> 
> Awesome! Everything looks nice. Thank you very much!
> 
> 
> 
> > I think the idea of listing translators in the info is excellent. I have no problem with that! :)
> 
> 
> 
> Should I use you outlook.com address you used to send a mail to the hydrogen-devel mailing list or another one?

pls use this one: aaronbcn@outlook.com

Many thanks!

**Pull request merged**
