### PR TITLE
Midi multi-track export (separate track for each instrument), SMF0 support, new MIDI tests

### PR DESCRIPTION
**Pull request by gloryofrobots**
Currently, H2 exports all instruments into one midi track.

If H2 is used to create midi drum tracks for later work in some kind of DAW then multitrack export (one track per instrument) is more convenient, because there is often a need to EQ-se each drum separately.

To provide this ability I made SMFWriter from SMF.h/smf.cpp an abstract class and made two subclasses for it: SMFWriterSingle and SMFWriterMulti.
I tried to leave previous export logic in SMFWriter as it was and injected some calls to virtual methods from subclasses.

For the GUI I added new ExportMidiDialog similar to ExportSongDialog but much simpler with only one combo box.

### CODE REVIEW

**Comment by gloryofrobots** [comment]
I changed midi files in functional tests because they contained 2018 year in one of the events. This was causing test failures because generated midi files and test files differ by one "year" byte

**Comment by elpescado** [comment]
That's cool! It would be nice to add functional test cases for this module.

And one more idea: ability to [export format 0 MIDI files](https://sourceforge.net/p/hydrogen/mailman/hydrogen-devel/thread/%21%26%21AAAAAAAAAAAYAAAAAAAAAIjujVqnwMREmSjYdYkAzl7CgAAAEAAAAPNIXOdfiLxInPtvYjkjDC8BAAAAAA%3D%3D%40gmail.com/#msg36440647).

**Comment by gloryofrobots** [comment]
Added functional test for multitrack export

**Comment by gloryofrobots** [comment]
I implemented SMF0 in recent commits. The export midi dialog now has three options:

- SMF1: export all instruments to a single track
- SMF1: export each instrument to separate track
- SMF0: export all events to one track

I am not 100% sure about my implementation. In comparison with SMF1 I changed file header with format=0 and num tracks=1, and put all events into one track. Please correct me if I am wrong. 

I successfully imported H2 generated SMF0 files into Guitar Pro 6, LMMS and Sekuiju, however, I had no access to hardware drums to test compatibility there.

**Comment by trebmuh** [comment]
I really like this idea!

Please @gloryofrobots , can you resolve the conflicts here for me to be able to test this on a current git master head?

**Comment by gloryofrobots** [comment]
@trebmuh, thanks for your interest in this PR, conflicts are resolved.

Need to say there is an error in PreferencesDialog.cpp and it been there since I began to work on this PR

...hydrogen/src/gui/src/PreferencesDialog.cpp: In constructor 'PreferencesDialog::PreferencesDialog(QWidget*)':
...hydrogen/src/gui/src/PreferencesDialog.cpp:286:2: error: 'sBmaxLayers' was not declared in this scope
  sBmaxLayers->setValue( pPref->getMaxLayers() );
  ^

I commented those lines on my machine but did not include the fix for the merge commit.

I forgot to mention earlier that I changed the names of midi test files to include format specifics.
Right now in tests/data/functional there are  

smf0.test.ref.mid -> new
smf0.velocityautomation.ref.mid -> new
smf1.velocityautomation.ref.mid -> renamed velocityautomation.ref.mid
smf1multi.test.ref.mid -> new
smf1single.test.ref.mid -> renamed test.ref.mid

**Comment by mauser** [comment]
Hi! 

Thanks a lot for the pull request! 

I have no objections from the coding viewpoint, the code looks clean and has in my opinion no obvious problems. Haven't done any functional testing yet, it would be great if someone else with a MIDI background could jump in here and give feedback.

About the problem with the PreferencesDialog: Is it possible that this is a local problem on your PC which results from a merge conflict? On my PC, sBmaxLayers is defined in the auto-generated file ui_PreferencesDialog_UI.h, the way it should be. Maybe due to some reason, your ui_PreferencesDialog_UI.h is no in sync with the rest of the code.

**Comment by gloryofrobots** [comment]
Are you interested in merging this PR or is it an unnecessary feature? If you are, I will fix the conflicts.

**Comment by trebmuh** [comment]
@mauser said he's above, I think that from reading at your description, it sounds good. I can try to have a go with it next week if you fix the conflicting files @gloryofrobots .

**Comment by elpescado** [comment]
I think it's a cool feature!

**Comment by gloryofrobots** [comment]
Conflicts are resolved. I manually tested multitrack and smf0 export in Ardour, Rosegarden, Tux Guitar and Sunvox. @trebmuh please test this branch if you can

**Comment by trebmuh** [comment]
Sorry for the delay, I was side tracked by a bunch of stuff.
Will try this tomorrow I guess.
Feel free to ping me in 3 or 4 days if I'm not replying here.

**Comment by trebmuh** [comment]
I've built from your midi-multitrack branch.

There might be something I don't understand here. I was under the impression that using "`SMF1: export each instrument to separate track`", H2 would export each instrument (ie: kick, snare, closed hihat,...) to its own midifile. So I've set up a very simple pattern like this:

H2-simple pattern

and then, I exported it using: Ctrl+M (= export MIDI file), choose "`Modus: SMF1: export each instrument to separate track`", then clicked "Export".

But I have only one file... is this to be expected? :confused:

**Comment by gloryofrobots** [comment]
Yes this is correct behavior. It must export to single file with multiple midi tracks declared inside of it. Then when you import this file in DAW you are expected to import multiple tracks in your project. 
I`ve just tested this branch again in the same Ardour 5.12 and it worked as expected. I attached Ardour screenshot and generated midi file for one of H2 demos.
[Pictures.zip](https://github.com/hydrogen-music/hydrogen/files/4413016/Pictures.zip)
Can you please test it again and send me your generated midi file and H2 file

**Comment by elpescado** [comment]
There should be always only one MIDI file, but its internal structure would be different. [Wikipedia article](https://en.wikipedia.org/wiki/MIDI#Standard_files) might cast some light on it.

**Comment by trebmuh** [comment]
Ok, I don't know what I did yesterday, but it works for me now!

Something which can be handy would be to add silence until the end of the pattern. Examples here:
Screenshot from 2020-04-01 08-47-44

All the green arrows (which likely belong to the same pattern) should finish at the same time. Same for the red arrows. This would help:
1. to visualize the pattern more easily
2. to understand how the song is constructed
3. to mix more easily (think adding a reverb' as an example where you would need to add space after the last note for the reverb's tail)

It looks very good by the way!

PS: 
> I noticed that select widget does not remember you previous choice. In my case it was a common mistake to export to smf1 single track instead of smf1 multitrack because of that

I agree, it would be need to make this choice persistent with the last one the user choosed.

**Comment by gloryofrobots** [comment]
@trebmuh Thank you very much for the feedback. 

How can I add silences in midi file?
As I understand midi format does not have a concept of bars and rests.
It is essentially a stream of events and meta events. Meta events include copyright, tempo, time signature, track info, etc. 
Events look like <timedelta, channel 1, note C4 ON> <timedelta, channel 1, note C4 OFF>. 

Please correct me if I`m wrong

**Comment by trebmuh** [comment]
I'll take your word for it. I don't know the MIDI specification.

So if not possible, then last thing from my point of view is: can you make the select widget to remember previous choice from the user? Including:
- SMF1-multi, SMF1-single, or SMF0
- the location where to save the file
- the name of the to-be-saved file

Also, I'm pinging the usual suspect here @mauser @jeremyz @elpescado @theGreatWhiteShark to check if that would be all good for you for this to be merged in master before 1.0.0 since I personally think that this is a very great enhancement to H2. What do you guys think?

**Comment by trebmuh** [comment]
>@trebmuh Thank you very much for the feedback.

You're really welcome. Sorry that I've been able to test it before. And thank you very much for this job!

----

I'll take your word for it. I don't know the MIDI specification.

So if not possible, then last thing from my point of view is: can you make the select widget to remember previous choice from the user? Including:
- SMF1-multi, SMF1-single, or SMF0
- the location where to save the file
- the name of the to-be-saved file

Also, I'm pinging the usual suspect here @mauser @jeremyz @elpescado @theGreatWhiteShark to check if that would be all good for you for this to be merged in master before 1.0.0 since I personally think that this is a very great enhancement to H2. What do you guys think?
Also @thijz you usually have a good overview about MIDI, what do you think about this?

**Comment by jpcima** [comment]
>Something which can be handy would be to add silence until the end of the pattern. Examples here:

>How can I add silences in midi file?

The SMF tracks are terminated by end-of-track event, a possibility might be to set delta-time on these.

**Comment by gloryofrobots** [comment]
@jpcima  Thanks for the advice I will look into it. 
@trebmuh  I will implement export widget "memory" probably before the end of the week.

**Comment by trebmuh** [comment]
@gloryofrobots ok, nice. Please, feel free to ping me when you need another test. I'll try to get it done more quickly this time !
.
.
.
... but no promise :wink:

**Comment by mauser** [comment]
@trebmuh : I'm willing to merge this, but i think it makes sense to wait until the work is finally finished.

**Comment by trebmuh** [comment]
Nice!

**Comment by gloryofrobots** [comment]
Update about midi padding, the result is mixed.
I added END_OF_TRACK events with timedelta = max timedelta in the pattern.

The generated midi file in human readable form looks like this (generated with py_midicsv)
First column is a track number, second column is a tick, third is a type and rest is a datum 
```
0, 0, Header, 1, 4, 192
1, 0, Start_track
1, 0, Copyright_t, "(C) Unknown 2020"
1, 0, Title_t, "Untitled Song"
1, 0, Tempo, 500000
1, 0, Time_signature, 4, 2, 24, 8
1, 1, End_track
2, 0, Start_track
2, 0, Title_t, "Kick"
2, 0, Note_on_c, 9, 36, 101
2, 48, Note_off_c, 9, 36, 101
2, 384, Note_on_c, 9, 36, 101
2, 432, Note_off_c, 9, 36, 101
2, 720, End_track
3, 0, Start_track
3, 0, Title_t, "Snare"
3, 192, Note_on_c, 9, 38, 101
3, 240, Note_off_c, 9, 38, 101
3, 576, Note_on_c, 9, 38, 101
3, 624, Note_off_c, 9, 38, 101
3, 720, End_track
4, 0, Start_track
4, 0, Title_t, "Stick"
4, 96, Note_on_c, 9, 37, 101
4, 144, Note_off_c, 9, 37, 101
4, 288, Note_on_c, 9, 37, 101
4, 336, Note_off_c, 9, 37, 101
4, 480, Note_on_c, 9, 37, 101
4, 528, Note_off_c, 9, 37, 101
4, 672, Note_on_c, 9, 37, 101
4, 720, Note_off_c, 9, 37, 101
4, 720, End_track
0, 0, End_of_file
```

I tested it in Ardour, Qtractor and Rosegarden

so far only Rosegarden understands what we are trying to achieve.
Screenshots from all programs and midi itself are in attachement.

I have not pushed this changes yet because code is a mess right now and because I am not sure we need to do it.

Do we need to implement it if most of the DAWs ignore End_track events and use only note events?

If this feature is really necessary the only way I see to implement it is to stretch note durations so 
they are going to fill measure until the next note or end of pattern. But I do not advise to do it. 
I fear long drum notes can cause some unwanted effects on a drum synthesisers.

@trebmuh Please tell me what do you think?

Screenshots and midi file here 
[midi-padding-screens.zip](https://github.com/hydrogen-music/hydrogen/files/4423721/midi-padding-screens.zip)

**Comment by trebmuh** [comment]
I'm wondering too. :sunglasses: 
@jpcima any wise advice maybe?

**Comment by jpcima** [comment]
Does it make a difference to introduce a dummy meta-event, eg. Text, before EOT with the delta-time?

**Comment by gloryofrobots** [comment]
I inserted Marker, Text and Lyric dummy meta-events before EndOfTrack.
It did nothing. 

Test Midi files here. EOT-s are not on the same tick but dummy events are all at 720
[midi-padding-hacks.zip](https://github.com/hydrogen-music/hydrogen/files/4426646/midi-padding-hacks.zip)

Probably anything which is not a note event will be ignored by most of the software on import.
Rosegarden is special here because it is very midi friendly.
@jpcima  @trebmuh where do we go from here?

**Comment by mauser** [comment]
Maybe it makes sense to split-off the track length issue into a different Github Issue and finalize this Pull Request first (if it's ready).

**Comment by trebmuh** [comment]
I totally agree with @mauser .
Is that easily possible to implement the export widget "memory" and then, this PR will be all good to be merged into master @gloryofrobots ?

**Comment by gloryofrobots** [comment]
I`ve pushed widget "memory" already but I need to discuss some things.

I added to preferences last midi export directory and last selected midi format but not filename.

It is quite easy to do but it will be inconsistent with song export dialog. 
So in song export and in midi export filename is a song name or "Untitled song" if song is not saved.
You can change it, of course, but it will not be saved.

I think it is a good behavior if you are working with multiple projects at once and you are exporting them into one folder.
Which is exactly my workflow. If filename is remembered then I need to retype it constantly when switching and exporting.

If you are working with one project at a time and you need to name your midi file in some specific way then saving filename has sense.

Anyway I think export dialogs must be consistent with each other. Currently song export does not save export dir in the preferences.
Instead it relies on a static variable 

```
void ExportSongDialog::on_browseBtn_clicked()
{
    static QString lastUsedDir = QDir::homePath();

```
So it remembers directory but only during one session until H2 is closed.
There is actually field in Preferences class ```m_sExportDirectory``` for this  but it is not used in client code.

@trebmuh @mauser 
Do I need to save filename on midi export as I was asked before?
Do I need to change song export to match midi export behavior? (probably separate PR is better for this)

As an afterthought I actually like the idea of storing filename in static variable until program is closed and dirname in preferences permanently

**Comment by mauser** [comment]
Hi! 

Well spotted. I rewrote the ExportDialog more or less completely some years ago, but that bit with filename/directory was never finished. This is why you found that variable in the preferences class... There must be a Github Ticket somewhere with a corresponding feature request. From my point of view, it would be great if you could implement this aspect in both Export Dialogs in the same way!!

> As an afterthought I actually like the idea of storing filename in static variable until program is closed and dirname in preferences permanently

That's a good idea, it makes sense for me.

**Comment by trebmuh** [comment]
Sounds all good to me.

**Comment by trebmuh** [comment]
Sounds all good to me. I'll try to rebuild that and play a bit with it tomorrow if time permits.

**Comment by gloryofrobots** [comment]
@trebmuh Please wait until I complete everything.  I will notify you when I`m done

**Comment by gloryofrobots** [comment]
I`ve implemented all dialog changes discussed before. 

So in both ExportSongDialog and ExportMidiDialog
- export directories are saved in Preferences
- export filenames stored in static class variables
```
static QString  sLastFilename;
```

Also I added validation check before export starts for valid parent directory path,
because if user manually edits filename text field and writes there some nonsense the export process will go without a warning but nothing will be created.

@trebmuh If you can please test those new changes

**Comment by trebmuh** [comment]
@gloryofrobots : I've been playing a bit with that, and everything looks good to me. Congratz and thanks!

**Comment by mauser** [comment]
Perfect, merged! 

@gloryofrobots : Thanks a lot for your work and your very fast response in the last days!!

**Comment by gloryofrobots** [comment]
Thanks. My pleasure to help)

**Pull request merged**
