### PR TITLE
Qt5 port

### PR DESCRIPTION
**Pull request by elpescado**
This branch adds compile time option to use Qt5. Qt5 support is optinal and by default off. To enable, `-DWANT_QT5=1` option has to be passed to `cmake`. This branch is pretty rudimentary - it does only the necessary changes required to compile with Qt5. I hadn't had time to test Qt5 build thoroughly - so I consider it "buildable", not "working". Qt4 build shouldn't be affected.

I have tested this branch on Mac and Debian, both Qt4 (4.8.6) and Qt5 (5.6.1).

One issue I have noticed is that Plastique, default hteme used by Hydrogen is missing in Qt5, so Hydrogen looks a little weird. Changing theme to Fusion fixes this.

I'd be grateful for testing this branch.

Regards,
Przemek

PS. I might be unavailable for the next 2-3 weeks.

### CODE REVIEW

**Comment by mauser** [comment]
Hi! 

Perfect! 
Apart from the theme-problems you mentioned everything works for me. Did you make the QT5 support optional only for testing or is there a reason why we should keep that optional in the future? 

Until now my thought was that we go qt5-only with Hydrogen 0.9.8. Especially since it is hard to avoid problems when using qt5-only methods..

**Comment by mikotoiii** [comment]
I went to test the Windows builds with Qt5, but the recently updated
scripts and cmakelists weren't merged into the repo, then I got distracted
with other things and ran out of time for today. I'll see about cloning the
repo and syncing it with the latest master tomorrow.

On Sep 6, 2016 15:40, "Sebastian Moors" <notifications@github.com> wrote:

Hi!

Perfect!
Apart from the theme-problems you mentioned everything works for me. Did
you make the QT5 support optional only for testing or is there a reason why
we should keep that optional in the future?

Until now my thought was that we go qt5-only with Hydrogen 0.9.8.
Especially since it is hard to avoid problems when using qt5-only methods..

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hydrogen-music/hydrogen/pull/409#issuecomment-245048065>,
or mute the thread

**Comment by elpescado** [comment]
> Did you make the QT5 support optional only for testing

Yes, I made it optional because I really didn't have time to test it beyond basic "compile and see whether it starts at all". Once Qt5 build is thoroughly tested, I see no point in keeping Qt4 compatibility, as Qt4 library does not seem maintained and most distros have alreadey moved to Qt5. Moreover, I think that Qt5 brings better support for non-Linux platforms (high-resolution screens etc).

**Comment by trebmuh** [comment]
Great to see Qt5 coming in. Congratz!

**Comment by mauser** [comment]
Hi,

this branch has been merged now with the master branch.

**Comment by trebmuh** [comment]
Hi guys,
I just rebuild from current GIT master : https://github.com/hydrogen-music/hydrogen/commit/afa967b80f4c4c6806fc7bdbd4badd7292be3768 and enabled qt5. The compilation went fine (both amd64 and i386) and so far, the test I did with Hydrogen doesn't show anything suspect. I'll be playing a bit more and the next days and will report if I find something strange.
Cheers.

**Comment by trebmuh** [comment]
I did rebuild git from https://github.com/hydrogen-music/hydrogen/commit/b19ba20489588e4b40031235ecd3157610760a85 2 days ago and have been looking around, nothing seems to be wrong. I'll let you guys know if something hits my eyes.

Thanks!

**Pull request merged**
