### PR TITLE
Added Rename function to instrument context menu 

### PR DESCRIPTION
**Pull request by pvint**
For Issue #11 
snapshot31

### CODE REVIEW

**Comment by mauser** [comment]
Perfect, merged!

**Comment by trebmuh** [comment]
Thanks guys!
Added here : https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-1.0

**Comment by trebmuh** [comment]
Fresh rebuild from https://github.com/hydrogen-music/hydrogen/commit/c59eb82c1964fc382960ad579eca129d7506ff51 tested, everything is working fine.

**Comment by pvint** [comment]
👍  Thanks for the test @trebmuh

**Comment by trebmuh** [comment]
You're really welcome.
I don't really know why but it sounds more logical to me to put the "Rename Instrument" item above the "Delete instrument"'s one. If you find this idea useful, great. If not, not point taken against me, just drop this message/idea :)

**Comment by trebmuh** [comment]
Great! :+1:

**Pull request merged**
