### PR TITLE
hydrogen.cpp: Added fallback in case desired MIDI driver cannot be found...

### PR DESCRIPTION
**Pull request by milasudril**
I got a problem when there is no support for the default MIDI driver upon first startup. This change looks through all available MIDI drivers, given a currently fixed priority list.

### CODE REVIEW

**Comment by trebmuh** [comment]
@milasudril and @mauser : any news on this one? Does that need testing? If so, what could be a use-case I could test?

**Comment by milasudril** [comment]
Disable the default MIDI driver when configuring hydrogen. (Was it ALSA, I do no remember now). It should choose another instead. Before this change,Hydrogen starts without MIDI support in that case.

**Comment by trebmuh** [comment]
OK, so it's about a configure option before building/compiling Hydrogen if I got it right. Thanks.

**Comment by theGreatWhiteShark** [comment]
Superseded by #1397

**Comment by theGreatWhiteShark** [comment]
Thanks for the input and sorry it took so long to incorporate it

**Pull request closed without merging**
