### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by theGreatWhiteShark** [comment]
Hey @trebmuh ,

have you run the updateTranslations.sh script locally? I'm afraid there are still more than one unfinished translation out there.

**Comment by trebmuh** [comment]
No I didn't, I've only translated this through the github online website.

**Comment by theGreatWhiteShark** [comment]
Alight. I will update the translation files during the next days so you can edit the remaining ones online again.

**Comment by theGreatWhiteShark** [comment]
@trebmuh updated translations should be on `master` now

**Comment by trebmuh** [comment]
@theGreatWhiteShark : thanks, pull request made.

**Pull request merged**
