### PR TITLE
tweak about dialog

### PR DESCRIPTION
**Pull request by theGreatWhiteShark**
- replaced old logo by current one
- replaced Sourceforge project page by Github one
- added link to Github Discussion
- made all the URLs clickable
- added myself to the list

about_dialog

### CODE REVIEW

**Comment by trebmuh** [comment]
LGTM, nice.
I've added a contact email for me.

**Comment by trebmuh** [comment]
>  I'd suggest adding an empty line above "Website".

Which I hopefully just did (not a programmer here, please double-check).

**Comment by theGreatWhiteShark** [comment]
> Which I hopefully just did (not a programmer here, please double-check).

+1

I increased the height of the widget.

**Comment by trebmuh** [comment]
@theGreatWhiteShark rebuild from ecc6339, I'm seeing that the email addresses do not seems to be used at all on the GUI:

example with mine:

h2-email-adresses-not-used

I'm not sure if that's intended or not but I thought I should mention it here.

**Comment by theGreatWhiteShark** [comment]
> I'm seeing that the email addresses do not seems to be used at all on the GUI

@trebmuh Yeah, I was surprised to find them in the code because email addresses weren't displayed before those changes either. This feels kinda right because there is no obvious reason to publish the email addresses of every contributor (except for the maintainer) so it was maybe intended. Also, the list does not contain all contributors from recent years. Maybe a note like "A full list of all contributors can be found on Github [URL]" should be added at the bottom.

**Comment by trebmuh** [comment]
> there is no obvious reason to publish the email addresses of every contributor

I've got one. As a translator, I like to leave a way of contacting me for a translation issue. I helps me to get feedback about the translations.

> Also, the list does not contain all contributors from recent years. Maybe a note like "A full list of all contributors can be found on Github [URL]" should be added at the bottom.

That could be great if we could separate between active contributors and inactive contributors. Audacity does that.

@mauser thoughts?

**Comment by mauser** [comment]
Hi! 

about the missing email info: I don't know about the idea behind that, but it seems that it has been the same for the last 14 years (and maybe more). 

about the separation between active/inactive authors: I suppose it would be easier to add a note, as @theGreatWhiteShark  mentioned. Otherwise someone has to actively keep that list in the about dialog maintained. I would think that this will work for the next month and then it will be forgotten :smiley:

**Comment by cme** [comment]
Or prioritise contributors by time-weighted commit count from the 'git log' of the release branch? :D

**Comment by trebmuh** [comment]
@mauser so, removing what's written currently and replacing it with a link to github?

**Comment by theGreatWhiteShark** [comment]
> As a translator, I like to leave a way of contacting me for a translation issue.

Translation is another point. None of the text in the About dialog gets translated (and I think this is fine since almost nobody reads through it and some more work for the translators). 

> I helps me to get feedback about the translations.

Right below the `About` dialog in the menu is the `Report Bug`. This is a better way for communicating translation issues (unlike you some translators might have done a one-time job and might not respond to mails)

>  I would think that this will work for the next month and then it will be forgotten

:smile: Yeah, I think so too.

> so, removing what's written currently and replacing it with a link to github?

Hmm. I would keep it because it just feels plain wrong to delete the list of former contributors from the GUI. We can state something like "This list is outdated. For the full list of contributors and to share ideas or ask for help please visit the project's page on Github."

**Comment by trebmuh** [comment]
> >    As a translator, I like to leave a way of contacting me for a translation issue.
>
> Translation is another point. None of the text in the About dialog gets translated (and I think this is fine since almost nobody reads through it and some more work for the translators).

You misinterpreted what I was saying here. I didn't say that those parts needs to be translated. I say that as a translator, I'd like to be able to put an email address in this "Authors" tab then, if a French-speaking dude want to contact me about the French translation (reporting a typo/mistake/suggestion/...whatever), then he can.


> Right below the About dialog in the menu is the Report Bug. This is a better way for communicating translation issues

With over 10 years of translating GUI for free software, I found out that leaving a simple email address here is more likely to help me collecting feedback than requiring a random dude to subscribe to a dev-ML or github.


>  (unlike you some translators might have done a one-time job and might not respond to mails)

I didn't say it should be compulsory, I think that is fine to leave it up to the translator to put an email address here or not


> I would think that this will work for the next month and then it will be forgotten

It could well be a part of each release cycle. Anyway, that was only a suggestion.


> Hmm. I would keep it because it just feels plain wrong to delete the list of former contributors from the GUI. We can state something like "This list is outdated. For the full list of contributors and to share ideas or ask for help please visit the project's page on Github."

It even feel stranger! If that list is outdated, then it need either to be updated or to be removed and replaced by a link.

**Comment by theGreatWhiteShark** [comment]
> You seems to misunderstand or misinterpreted what I was saying here. I didn't say that those parts needs to be translated. I say that as a translator, I'd like to be able to put an email address in this "Authors" tab then, if a French-speaking dude want to contact me about the French translation (reporting a typo/mistake/suggestion/...whatever), then he can.

Hey. Yeah, I should had spent more words on this. I did got your point but I think it's a little bit awkward to have to whole GUI translated except of the term "French translation". For language based on Latin characters this might not be a big deal but maybe for other it does. So, how about using native version of this phrase (without being translatable)? This way it doesn't require knowledge about English at all to get in touch with the translator.

> It even feels stranger! If that list is outdated, then it either needs to be updated or to be removed and replaced by a link. Making it comprehensive for a reader-without-any-history-with-h2-development.

Well, it wouldn't be the best solution from the technical level but maybe the least offensive one.

Anyway.

> It could well be a part of each release cycle.

I guess you are right and it's a good idea to list the active developers.

**Comment by trebmuh** [comment]
> Hey. Yeah, I should had spent more words on this. I did got your point but I think it's a little bit awkward to have to whole GUI translated except of the term "French translation". For language based on Latin characters this might not be a big deal but maybe for other it does. So, how about using native version of this phrase (without being translatable)? This way it doesn't require knowledge about English at all to get in touch with the translator.

Agreed. I would propose another tab in this "about" window: About/Authors/Translators/License (like it is for many software). In this new "Translators" tab, we could then have a list of language and translators in native languages.

@theGreatWhiteShark : do you think we should open a new issue/PR for that?

**Comment by theGreatWhiteShark** [comment]
> do you think we should open a new issue/PR for that?

Yes. Without an issues it's likely we loose sight of this.

**Pull request merged**
