### PR TITLE
adding a man page

### PR DESCRIPTION
**Pull request by trebmuh**
As discussed on the devel ML, here is a manpage.

To write it I :

1. started it with the 0.9.4 from the debian packaging : https://anonscm.debian.org/cgit/pkg-multimedia/hydrogen.git/tree/debian/hydrogen.1
2. took off the lash related stuffs (`--lash-no-start-server` and `--lash-no-autoresume`)
3. took inspiration from other software manpage

I hope this is fine.

It would be great if it could be incorporated in the build process (if someone would like to take care of that).

### CODE REVIEW

**Comment by mauser** [comment]
Thanks a lot, i will see if i can integrate it in the build process..

**Comment by trebmuh** [comment]
:+1:

**Comment by trebmuh** [comment]
Hi @mauser , I don't know if you have a todo list when you are releasing a new version. Is so, would you think that integrating a review of the man page would be interesting? There is a date and a version number in there which would need to be updated in there.

**Comment by trebmuh** [comment]
Found! https://github.com/hydrogen-music/hydrogen/wiki/Test-checklist

**Comment by mauser** [comment]
Hi! 

The correct place would be the DEVELOPERS file.  I've mentioned the man page there and will remove the sentence from the wiki page (which is for testing hydrogen).

**Comment by trebmuh** [comment]
:+1:

**Pull request merged**
