### PR TITLE
Print messages some basic core classes

### PR DESCRIPTION
**Pull request by theGreatWhiteShark**
When debugging Hydrogen while trying to fix a bug I spend most of the time with figuring out the state of the application in this or that context. Using the new methods one can simply print the content of a `core/Basics` class to the `DEBUGLOG` or to `std::out`. That might help. I added the latter one because our custom log is not that useful when hunting done things resulting in a crash of H2.

Also, I omitted some things: All audio data (in the `Sample` and `DrumkitComponent`) and the `PanEnvelop` and `VelocityEnvelope` members in `Sample` because they are implemented as `std::unique_ptr` and I don't want to alter the implementation.

```c++
pDrumkit->Print();
```

or 

```c++
std::cout << pDrumkit << std::endl;
```

resulting in 

```
[Drumkit]
  path: /home/phil/git/hydrogen/src/tests/data///drumkits/baseKit
  name: H2 test DK
  author: Zurcher Jérémy
  info: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta name="qrichtext" content="1" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body style=" font-family:'Helvetica'; font-size:10pt; font-weight:400; font-style:normal;">
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"></p></body></html>
  license: MIT
  image: 
  imageLicense: undefined license
  samples_loaded: 1
  [InstrumentList]
    [Instrument]
      id: 0
      name: Crash
      drumkit_name: H2 test DK
      gain: 1
      volume: 1
      pan_l: 0.5
      pan_r: 1
      peak_l: 0
      peak_r: 0
      [ADSR]
        attack: 0
        decay: 0
        sustain: 1
        release: 5800
        state: 0
        ticks: 0
        value: 0
        release_value: 0
      filter_active: 0
      filter_cutoff: 1
      filter_resonance: 0
      random_pitch_factor: 0
      pitch_offset: 0
      midi_out_note: 60
      midi_out_channel: -1
      stop_notes: 1
      sample_selection_alg: 0
      active: 1
      soloed: 0
      muted: 0
      mute_group: -1
      queued: 0
      fx_level: [ 0 0 0 0 ]
      hihat_grp: -1
      lower_cc: 0
      higher_cc: 127
      is_preview_instrument: 0
      is_metronome_instrument: 0
      apply_velocity: 1
      current_instr_for_export: 0
      m_bHasMissingSamples: 0
      components:
        [InstrumentComponent]
          related_drumkit_componentID: 0
          gain: 1
          m_nMaxLayers: 16
          layers:
            [InstrumentLayer]
              gain: 1
              pitch: 0
              start_velocity: 0.5
              end_velocity: 1
              [Sample]
                filepath: /home/phil/git/hydrogen/src/tests/data///drumkits/baseKit/crash.wav
                frames: 134144
                sample_rate: 44100
                is_modified: 0
                [Loops]
                  start_frame: 0
                  loop_frame: 0
                  end_frame: 0
                  count: 0
                  mode: 0
                [Rubberband]
                  use: 0
                  divider: 1
                  pitch: 1
                  c_settings: 4
            [InstrumentLayer]
              gain: 1
              pitch: 0
              start_velocity: 0
              end_velocity: 0.5
              [Sample]
                filepath: /home/phil/git/hydrogen/src/tests/data///drumkits/baseKit/crash.wav
                frames: 134144
                sample_rate: 44100
                is_modified: 0
                [Loops]
                  start_frame: 0
                  loop_frame: 0
                  end_frame: 0
                  count: 0
                  mode: 0
                [Rubberband]
                  use: 0
                  divider: 1
                  pitch: 1
                  c_settings: 4
    [Instrument]
      id: 1
      name: Hi-Hat
      drumkit_name: H2 test DK
      gain: 1
      volume: 1
      pan_l: 1
      pan_r: 0.5
      peak_l: 0
      peak_r: 0
      [ADSR]
        attack: 0
        decay: 0
        sustain: 1
        release: 5800
        state: 0
        ticks: 0
        value: 0
        release_value: 0
      filter_active: 0
      filter_cutoff: 1
      filter_resonance: 0
      random_pitch_factor: 0
      pitch_offset: 0
      midi_out_note: 60
      midi_out_channel: -1
      stop_notes: 1
      sample_selection_alg: 0
      active: 1
      soloed: 0
      muted: 0
      mute_group: -1
      queued: 0
      fx_level: [ 0 0 0 0 ]
      hihat_grp: -1
      lower_cc: 0
      higher_cc: 127
      is_preview_instrument: 0
      is_metronome_instrument: 0
      apply_velocity: 1
      current_instr_for_export: 0
      m_bHasMissingSamples: 0
      components:
        [InstrumentComponent]
          related_drumkit_componentID: 0
          gain: 1
          m_nMaxLayers: 16
          layers:
            [InstrumentLayer]
              gain: 1
              pitch: 0
              start_velocity: 0
              end_velocity: 1
              [Sample]
                filepath: /home/phil/git/hydrogen/src/tests/data///drumkits/baseKit/hh.wav
                frames: 19200
                sample_rate: 44100
                is_modified: 0
                [Loops]
                  start_frame: 0
                  loop_frame: 0
                  end_frame: 0
                  count: 0
                  mode: 0
                [Rubberband]
                  use: 0
                  divider: 1
                  pitch: 1
                  c_settings: 4
    [Instrument]
      id: 2
      name: Snare
      drumkit_name: H2 test DK
      gain: 1
      volume: 1
      pan_l: 1
      pan_r: 1
      peak_l: 0
      peak_r: 0
      [ADSR]
        attack: 0
        decay: 0
        sustain: 1
        release: 5800
        state: 0
        ticks: 0
        value: 0
        release_value: 0
      filter_active: 0
      filter_cutoff: 1
      filter_resonance: 0
      random_pitch_factor: 0
      pitch_offset: 0
      midi_out_note: 60
      midi_out_channel: -1
      stop_notes: 1
      sample_selection_alg: 0
      active: 1
      soloed: 0
      muted: 0
      mute_group: -1
      queued: 0
      fx_level: [ 0 0 0 0 ]
      hihat_grp: -1
      lower_cc: 0
      higher_cc: 127
      is_preview_instrument: 0
      is_metronome_instrument: 0
      apply_velocity: 1
      current_instr_for_export: 0
      m_bHasMissingSamples: 0
      components:
        [InstrumentComponent]
          related_drumkit_componentID: 0
          gain: 1
          m_nMaxLayers: 16
          layers:
            [InstrumentLayer]
              gain: 1
              pitch: 0
              start_velocity: 0
              end_velocity: 1
              [Sample]
                filepath: /home/phil/git/hydrogen/src/tests/data///drumkits/baseKit/snare.wav
                frames: 27136
                sample_rate: 44100
                is_modified: 0
                [Loops]
                  start_frame: 0
                  loop_frame: 0
                  end_frame: 0
                  count: 0
                  mode: 0
                [Rubberband]
                  use: 0
                  divider: 1
                  pitch: 1
                  c_settings: 4
    [Instrument]
      id: 3
      name: Kick
      drumkit_name: H2 test DK
      gain: 1
      volume: 1
      pan_l: 1
      pan_r: 1
      peak_l: 0
      peak_r: 0
      [ADSR]
        attack: 0
        decay: 0
        sustain: 1
        release: 5800
        state: 0
        ticks: 0
        value: 0
        release_value: 0
      filter_active: 0
      filter_cutoff: 1
      filter_resonance: 0
      random_pitch_factor: 0
      pitch_offset: 0
      midi_out_note: 60
      midi_out_channel: -1
      stop_notes: 1
      sample_selection_alg: 0
      active: 1
      soloed: 0
      muted: 0
      mute_group: -1
      queued: 0
      fx_level: [ 0 0 0 0 ]
      hihat_grp: -1
      lower_cc: 0
      higher_cc: 127
      is_preview_instrument: 0
      is_metronome_instrument: 0
      apply_velocity: 1
      current_instr_for_export: 0
      m_bHasMissingSamples: 0
      components:
        [InstrumentComponent]
          related_drumkit_componentID: 0
          gain: 1
          m_nMaxLayers: 16
          layers:
            [InstrumentLayer]
              gain: 1
              pitch: 0
              start_velocity: 0
              end_velocity: 1
              [Sample]
                filepath: /home/phil/git/hydrogen/src/tests/data///drumkits/baseKit/kick.wav
                frames: 17477
                sample_rate: 44100
                is_modified: 0
                [Loops]
                  start_frame: 0
                  loop_frame: 0
                  end_frame: 0
                  count: 0
                  mode: 0
                [Rubberband]
                  use: 0
                  divider: 1
                  pitch: 1
                  c_settings: 4
  components:
    [DrumkitComponent]
      id: 0
      name: Main
      volume: 1
      muted: 0
      soloed: 0
      peak_l: 0
      peak_r: 0
```

### CODE REVIEW

**Comment by cme** [comment]
Awesome!

**Comment by theGreatWhiteShark** [comment]
I added another argument to the `Print()` and `toQString()` methods to yield an output that uses short handles, like the instrument name or the note position, to indicate larger member variables and whos output fits into one line.

I also set the shorter ones to be used with std::cout.

This way the output of e.g. the Song can be queried at different points without the log to be several MB.

**Comment by cme** [comment]
I tend to use qDebug() quite a lot while working in the GUI because it works well with Qt native types; any chance of adding support for that? It just needs a `QDebug operator<<(QDebug qd, ... )` function.

(I guess it doesn't even have to be a friend, you could do the whole thing as a template with something like:

```c++
template <class X>
QDebug operator<<(QDebug d, X *x) { d << (x? x->toQString("") : "(nullptr)" ); }

```
)

**Comment by theGreatWhiteShark** [comment]
> I tend to use qDebug() quite a lot while working in the GUI because it works well with Qt native types;

Hmm. So, I did had to write all these `string.toLocal8Bit().data()` in the ostreams after all? All those wasted hours. Well, at least I do not edit the `.ui` files by hand anymore :laughing: Maybe some day I will introduce myself properly to Qt.

**Review by cme — COMMENTED** [review]
Wouldn't it be better to make `toQstring` a virtual method of `H2Core::Object`, and implement the `<<` methods just once there as well, rather than implement them in each descendant class?

A default implementation could print at least the classname and address from the object pointer.

**Comment by theGreatWhiteShark** [comment]
> Wouldn't it be better to make toQstring a virtual method of H2Core::Object, and implement the << methods just once there as well, rather than implement them in each descendant class?

You are right. This makes the point of customization for all remaining classes more obvious.

It's a shame C++ does not feature reflection (at least not among it's stable features). Else we could provide a decent default.

**Review by cme — APPROVED** [review]
Awesome

**Pull request merged**
