### PR TITLE
#822 Set NSHighResolutionCapable to true in Info.plist

### PR DESCRIPTION
**Pull request by elpescado**
Fix for #822. It seems that one entry was missing in Hydrogen manifest (`Info.plist`), thus Hydrogen didn't advertise HiDPI capability.

### CODE REVIEW

**Comment by elpescado** [comment]
Mandatory screenshot:

Screenshot 2020-04-26 at 20 02 26

**Comment by mauser** [comment]
Hi! 

currently the linux build fails because the `plutil` can't be found. I suppose that this custom command should be added only for OS X

**Comment by elpescado** [comment]
Sorry about that! Should be fixed now.

**Comment by mauser** [comment]
Perfect, merged! I wish i would have a newer mac with a high-res display to test it :smile:

**Comment by cme** [comment]
1. I like the approach of using plutil to programmatically modify the Info.plist generated by cmake (cpack?). Much less pain than manually writing one (there's an old handwritten one that doesn't get used anymore). I'll probably try the same approach for adding associations for *.h2* files.
2. The high-DPI rendering is lovely, might make a motivating case for updating the icons & custom widgets to high dpi as well.

**Comment by elpescado** [comment]
> * I like the approach of using plutil to programmatically modify the Info.plist generated by cmake (cpack?). Much less pain than manually writing one (there's an old handwritten one that doesn't get used anymore). I'll probably try the same approach for adding associations for _.h2_ files.

Thanks! The other approach was to copy Info.plist template from CMake, customise it and use it with [`MACOSX_BUNDLE_INFO_PLIST`](https://cmake.org/cmake/help/v3.7/prop_tgt/MACOSX_BUNDLE_INFO_PLIST.html) instead of default one. Using `plutil` seems to me much more elegant.

> * The high-DPI rendering is lovely, might make a motivating case for updating the icons & custom widgets to high dpi as well.

Thanks again! When I was working on HiDPI screen support I wanted to create high resolution assets but, unfortunately, I soon realised that it required too much work, so I decided to focus on most important things, notably font rendering. If someone is interested in picking that up, I might try to dig up my old branch and share my efforts.

**Pull request merged**
