### PR TITLE
Undoable banks

### PR DESCRIPTION
**Pull request by blablack**
This pull request fixes: https://github.com/hydrogen-music/hydrogen/issues/267

After an instrument is dragged/dropped on the drumkit and a bank is added, when the user is trying to undo it, the bank is removed.

### CODE REVIEW

**Comment by mauser** [comment]
Hi Aurelien,

just tested the pull request and i'm running into an assertion (InstrumentEditor line 567). I'm just adding an instrument with component "B" to a drumkit which has instruments of component "A" with the "Merge" functionality and using undo (ctrl+z).

**Comment by blablack** [comment]
Hi @mauser 

I can't reproduce it:
- I tried with instrument with component "A" & "B" into drumkit with only "A"
- I tried with instrument with component "B" into drumkit with only "A"

In both cases undoing went fine.

Can you re-test again? maybe something i'm missing from your scenario?

**Comment by mauser** [comment]
Ah, retested and found the difference: You have to drag the instrument to the last position. But this error seems to occur also without your last changes if you drag an instrument to the end of the instrument list (this is important) and then do the undo. 

But back to this issue: If you're doing an undo while the layer tab is activated and show the new component (the one that will be deleted during undo), hydrogen will crash

**Comment by blablack** [comment]
@mauser Issue occurs as well with moving an instrument inside a drumkit.
Move it much fiurther than the last position, try to undo and Hydrogen will crash.

I found out what the problem is, I just need to find a solution:
- means this pull request is valid, the bug is unrelated
- I'll create a bug report for it
- I'll fix it in another branch

**Comment by mauser** [comment]
@blablack : Wow, that was fast. Thanks! I will be testing the new pull request later.. Btw, have you been able to reproduce the second problem i mentioned above? Or will this also be fixed by the other pull request? 

"But back to this issue: If you're doing an undo while the layer tab is activated and show the new component (the one that will be deleted during undo), hydrogen will crash"

**Comment by blablack** [comment]
@mauser : I kind of been able to reproduce it (in my case, Hydrogen doesn't
crash but the component is not removed). It wont be fix by the other pull
request (unrelated problem) - I'll need to fix it in this pull.

**Comment by blablack** [comment]
@mauser: fixed :)

**Comment by mauser** [comment]
Thanks again, everything merged now! I've just added a call to "	EventQueue::get_instance()->push_event( EVENT_SELECTED_INSTRUMENT_CHANGED, -1 );" to refresh the instrument editor after a "drop instrument" redo. Btw, please check your indentation settings :)

**Pull request merged**
