### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by xjjx**
Fixes for #190 , #220 , #222

### CODE REVIEW

**Comment by mauser** [comment]
Hi Pawel! You should have now (and even before) all permissions in Github to push to the hydrogen repository directly, so you can integrate your changes on your own without the need for pull requests! Btw. you have also Github permissions to merge pull requests from other people..

**Comment by xjjx** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Hi Sebastian,
 
Yeah, I know this, but IMHO it's better if one person keep watching on main repository. I'm also still not very familiar with git, so don't want to spoil anything there. Or rather - I read a lot about git and it's too complicated for me - I still prefer svn for rest of my small projects. You are probably the oldest active developer here, so if it's not problem for you , I will leave that pleasure for you ;-)
 
P.
 
Dnia Wtorek, 10 Lutego 2015 22:21 Sebastian Moors <notifications@github.com> napisa�(a)

Hi Pawel! You should have now (and even before) all permissions in Github to push to the hydrogen repository directly, so you can integrate your changes on your own without the need for pull requests! Btw. you have also Github permissions to merge pull requests from other people..

**Comment by mauser** [comment]
Hi Pawel,

your pull request has some conflicts (11) and most of them are in jack_output.cpp. Can you try to pull first and fix (and test) this conflicts on your side? Its hard for me to merge this file since i don't understand the audio engine details involved.

**Comment by mauser** [comment]
Btw., its always easier if you create seperate branches for seperates features / bug fixes, that makes life (and merging :) ) easier..

**Comment by xjjx** [comment]
Well, there was many changes around that code since my fixes. Hopefully I resolve all the problems by sync to upstream. Please try once again.

**Comment by mauser** [comment]
Merged! Will do more testing tomorrow..

**Pull request merged**
