### PR TITLE
improved NSM support

### PR DESCRIPTION
**Pull request by theGreatWhiteShark**
At the current state Hydrogen is, unfortunately, not compliant at all with the NSM standard and thus can only barely fits within session management. Most notable: due to the lack a automatic rewiring similar to #549 the per track output option is basically unusable. I added a couple of changes to make Hydrogen more compliant with the standard. This pull request is based on and supersedes  #773 

New features/improvements:
- All wiring of the JACK ports in session management (in presence of an application like `JackPatch` is persistent and will be restored when reloading the session. 
- User interface compliant with NSM standard
- H2 does use the name provided by the NSM server to store the song corresponding to the session in the designated session folder
- H2 is now able to support switching between different sessions without restarting the whole application. Instead, the new song is loaded and the audio driver restarted.
- H2 sends a 'dirty' flag to the NSM server to indicate unsaved changes.

Especially the first one gave me quite a headache. It turned out that the Song must already be present when starting the audio driver so JACK can create all track output ports along the main left and right output right away. Doing it at a later point in time won't work. I therefore introduced (among other changes) a new function called `Hydrogen::setInitialSong()` for a Song to be present when starting the audio driver without calling any of the audio driver-related routines in `Hydrogen::setSong()`. Note that while the checking whether H2 is under session management or not is specific to NSM, the solution should be extended to other session management systems like LADISH without a problem.

### CODE REVIEW

**Comment by trebmuh** [comment]
Nice! Pinging @houston4444 here since he's the dev of RaySession and might have some comments.

**Comment by Houston4444** [comment]
This sounds very good !
I made some quick tests, I see that client status becomes 'error' at client switch. (on both RaySession and Non Session Manager, tried with session duplicate).
```
[nsmd] Client "Hydrogen" replied with error:  (-4) in 110.714000ms

(E) ::int nsm_open_cb(const char*, const char*, const char*, char**, void*) Unable to handle opening action!
```
Dirty flag seems to works well !
Thanks

**Comment by theGreatWhiteShark** [comment]
That's odd. Seems like it couldn't load/create the other Song. I'll look into it. And add some more error messages that can be viewed in the session manager's log too.

I just also experienced that the rewiring was not persistent when loading very large session. Not quite sure whether something went wrong when rebasing on master or if there is still some bug under the hood.

@Houston4444 Do you also use `JackPatch` for rewiring in `RaySession`?

**Comment by Houston4444** [comment]
> @Houston4444 Do you also use JackPatch for rewiring in RaySession?

No, RaySession uses its own jackpatch (executable: ray-jackpatch), and I don't see any problem with it. 
I remember of many forgotten connections with Hydrogen (via proxy) and jackpatch (NSM's one) in the past.

**Comment by theGreatWhiteShark** [comment]
> No, RaySession uses its own jackpatch (executable: ray-jackpatch), and I don't see any problem with it.

Okay. I'll ensure this will work too.

> I remember of many forgotten connections with Hydrogen (via proxy) and jackpatch (NSM's one) in the past.

Yes, indeed. This is actually my true incentive in doing all the work with this pull request and I intend to fix it.

**Comment by Houston4444** [comment]
I think it's more a problem with jackpatch itself.
I'm pretty sure it comes from the way jackpatch saves its connections.
jackpatch saves its connections in a text/plain file and I think It has troubles with quotes which are often in jack port names in hydrogen (to symbolize the cymbal size).

I'm optimist that it will works well with ray-jackpatch. ray-jackpatch connect ports slowly (connect 200ms after last port created/modified) to let the client auto-connect its ports.
More, ray-jackpatch doesn't forget connections if ports are not present anymore at last save.

**Comment by theGreatWhiteShark** [comment]
> I made some quick tests, I see that client status becomes 'error' at client switch

Unfortunately, I can not reproduce this error (just tried with `non-session-manager` yet). Could you provided a step-by-step guide? Are you able to load the song you are switching to via the GUI or an OSC message?

> I think it's more a problem with jackpatch itself.

I also got that impression. Well, in case I can verify this I try to patch `jackpatch` instead.

**Comment by Houston4444** [comment]
> Unfortunately, I can not reproduce this error.
That's strange, it always happens in all switch situations on both NSM and RS.

here a part of the terminal when error happens:
`[nsmd] Waiting for announce messages from clients
[Hydrogen] Loading song /home/houston/NSM Sessions/test_hydroshark/Hydrogen.nPEUC.
[nsmd] Done. 1 out of 1 clients announced within the initialization grace period
[nsmd] Waiting for clients to reply to commands
[Hydrogen] Error: Unable to handle opening action!
[nsmd] Client sends clean
[nsmd] Client "Hydrogen" replied with error:  (-4) in 120.565000ms
`
I note the effort to make client stdout/stderr look like nsmd one, and it becomes more comprehensive to see who is talking.
If you try RS, you will see it was not needed for it.

**Comment by theGreatWhiteShark** [comment]
That's odd. So, it's not the actual loading of the Song but the handling of the Action to do so which fails.

Would you mind trying again with the code in this branch https://github.com/theGreatWhiteShark/hydrogen/tree/nsmReworkedDebug and report the output log? Maybe the action did not got registered properly (but no idea why that would be the case)

**Comment by Houston4444** [comment]
ok. here is the log (with RS, but it's probably not so different).

```
[Hydrogen-hydrogen]
[Hydrogen] Action type: OPEN_SONG
[Hydrogen::MidiActionManager] Registered action name: <<_PREVIOUS_BAR
[Hydrogen::MidiActionManager] Registered action name: >>_NEXT_BAR
[Hydrogen::MidiActionManager] Registered action name: BEATCOUNTER
[Hydrogen::MidiActionManager] Registered action name: BPM_CC_RELATIVE
[Hydrogen::MidiActionManager] Registered action name: BPM_DECR
[Hydrogen::MidiActionManager] Registered action name: BPM_FINE_CC_RELATIVE
[Hydrogen::MidiActionManager] Registered action name: BPM_INCR
[Hydrogen::MidiActionManager] Registered action name: EFFECT1_LEVEL_ABSOLUTE
[Hydrogen::MidiActionManager] Registered action name: EFFECT1_LEVEL_RELATIVE
[Hydrogen::MidiActionManager] Registered action name: EFFECT2_LEVEL_ABSOLUTE
[Hydrogen::MidiActionManager] Registered action name: EFFECT2_LEVEL_RELATIVE
[Hydrogen::MidiActionManager] Registered action name: EFFECT3_LEVEL_ABSOLUTE
[Hydrogen::MidiActionManager] Registered action name: EFFECT3_LEVEL_RELATIVE
[Hydrogen::MidiActionManager] Registered action name: EFFECT4_LEVEL_ABSOLUTE
[Hydrogen::MidiActionManager] Registered action name: EFFECT4_LEVEL_RELATIVE
[Hydrogen::MidiActionManager] Registered action name: FILTER_CUTOFF_LEVEL_ABSOLUTE
[Hydrogen::MidiActionManager] Registered action name: MASTER_VOLUME_ABSOLUTE
[Hydrogen::MidiActionManager] Registered action name: MASTER_VOLUME_RELATIVE
[Hydrogen::MidiActionManager] Registered action name: MUTE
[Hydrogen::MidiActionManager] Registered action name: MUTE_TOGGLE
[Hydrogen::MidiActionManager] Registered action name: NEW_SONG
[Hydrogen::MidiActionManager] Registered action name: OPEN_SONG
[Hydrogen::MidiActionManager] Registered action name: PAN_ABSOLUTE
[Hydrogen::MidiActionManager] Registered action name: PAN_RELATIVE
[Hydrogen::MidiActionManager] Registered action name: PAUSE
[Hydrogen::MidiActionManager] Registered action name: PLAY
[Hydrogen::MidiActionManager] Registered action name: PLAY/PAUSE_TOGGLE

[ray-daemon]Client "Hydrogen" replied with error:  (-4)

[Hydrogen-hydrogen]
[Hydrogen::MidiActionManager] Registered action name: PLAY/STOP_TOGGLE
[Hydrogen::MidiActionManager] Registered action name: PLAYLIST_NEXT_SONG
[Hydrogen::MidiActionManager] Registered action name: PLAYLIST_PREV_SONG
[Hydrogen::MidiActionManager] Registered action name: PLAYLIST_SONG
[Hydrogen::MidiActionManager] Registered action name: QUIT
[Hydrogen::MidiActionManager] Registered action name: RECORD/STROBE_TOGGLE
[Hydrogen::MidiActionManager] Registered action name: RECORD_EXIT
[Hydrogen::MidiActionManager] Registered action name: RECORD_READY
[Hydrogen::MidiActionManager] Registered action name: RECORD_STROBE
[Hydrogen::MidiActionManager] Registered action name: REDO_ACTION
[Hydrogen::MidiActionManager] Registered action name: SAVE_SONG
[Hydrogen::MidiActionManager] Registered action name: SAVE_SONG_AS
[Hydrogen::MidiActionManager] Registered action name: SELECT_AND_PLAY_PATTERN
[Hydrogen::MidiActionManager] Registered action name: SELECT_INSTRUMENT
[Hydrogen::MidiActionManager] Registered action name: SELECT_NEXT_PATTERN
[Hydrogen::MidiActionManager] Registered action name: SELECT_NEXT_PATTERN_CC_ABSOLUTE
[Hydrogen::MidiActionManager] Registered action name: SELECT_NEXT_PATTERN_PROMPTLY
[Hydrogen::MidiActionManager] Registered action name: SELECT_NEXT_PATTERN_RELATIVE
[Hydrogen::MidiActionManager] Registered action name: SELECT_ONLY_NEXT_PATTERN
[Hydrogen::MidiActionManager] Registered action name: STOP
[Hydrogen::MidiActionManager] Registered action name: STRIP_MUTE_TOGGLE
[Hydrogen::MidiActionManager] Registered action name: STRIP_SOLO_TOGGLE
[Hydrogen::MidiActionManager] Registered action name: STRIP_VOLUME_ABSOLUTE
[Hydrogen::MidiActionManager] Registered action name: STRIP_VOLUME_RELATIVE
[Hydrogen::MidiActionManager] Registered action name: TAP_TEMPO
[Hydrogen::MidiActionManager] Registered action name: TOGGLE_METRONOME
[Hydrogen::MidiActionManager] Registered action name: UNDO_ACTION
[Hydrogen::MidiActionManager] Registered action name: UNMUTE
[Hydrogen] Error: Unable to handle opening action!
```

**Comment by theGreatWhiteShark** [comment]
Okay. With `raysession` I'm not able to start up H2 at all. But I see why this is the case: the session manager needs a lot more time to respond to the announce message than `non-session-manager` and I assumed the opening to already be successful before starting up the GUI. Maybe this is responsible for your issue too.

I'll think about a more resilient way of implementation to make it work with both of them.

**Comment by theGreatWhiteShark** [comment]
@Houston4444 I applied some changes regarding the timing. Now I'm able to start H2 using `raysession` as well as to switch between different sessions. 

Could you try again on your end?

Thanks a lot for your input! :)

**Comment by Houston4444** [comment]
I tried.
So sorry, error is still there !

**Comment by theGreatWhiteShark** [comment]
Hmmm.. very strange. If I understand my own code, all occasions of "Unable to handle opening action!" should be at least accompanied with another, unformatted message to stdout. But there is nothing. No idea what went wrong here.

**Comment by Houston4444** [comment]
Now this seems to work, this "return true" was probably missing !

**Comment by theGreatWhiteShark** [comment]
Wow. I thought having `cmake` would save us from such kind of trouble. But I'm glad it's now working at your end :)

**Comment by Houston4444** [comment]
Hi. I've just seen something is improvable. With your PR hydrogen sends mannnnnnnnnny dirty states to the server.
Exemple of RS output:

```
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends clean
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends clean
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends clean
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
[ray-daemon]hydrogen_2 sends dirty
```
I think I would be so hard to send dirty state only if it had change.

Something else (really not strong), It would be quite prettier if hydrogen could reply the fact it is ready when the window has been displayed. RaySession (optionally) tries to keep its window in front of other windows while clients are opening. But it's maybe quite hard to do, don't consider this if it is too hard to do.

**Comment by theGreatWhiteShark** [comment]
> With your PR hydrogen sends mannnnnnnnnny dirty states to the server.

Indeed. I totally missed that. Thanks for pointing it out :). I can't test it right now but the last commit should fixed this behavior.

**Comment by theGreatWhiteShark** [comment]
> Something else (really not strong), It would be quite prettier if hydrogen could reply the fact it is ready when the window has been displayed.

Could you point me to how to implement this? I don't find it in the [online documentation](http://non.tuxfamily.org/nsm/API.html) of the NSM standard.

Or is it related to the open callback?

**Comment by Houston4444** [comment]
> Could you point me to how to implement this? I don't find it in the online documentation of the NSM standard.

No no, it's not specified in NSM documentation at all. Just, almost NSM clients behave this way.
As I said, RaySession (optionally) tries to keep its window in front of others while its clients are opening. It works only if clients replies they are ready after their window apparition. So, if it is simple to do, you could do that and I'll be happy, else do not take your head for this very trivial thing, in the worst case RaySession window will be behind hydrogen's one ;) .

**Comment by theGreatWhiteShark** [comment]
Sure, why not.

> It works only if clients replies they are ready after their window apparition

Two questions: 
1. What is "ready"? Is the the moment the song was opened, the window was generated, H2 is ready to play back audio, every last bit of code of the init procedure had been executed or something else?
2. How do I tell the session manager about the readiness? Via a specific OSC message?

**Comment by Houston4444** [comment]
> Two questions:
> 
> What is "ready"? Is the the moment the song was opened, the window was generated, H2 is ready to play back audio, every last bit of code of the init procedure had been executed or something else?
> How do I tell the session manager about the readiness? Via a specific OSC message?

I say "ready" for the moment the OSC server of the client (here Hydrogen) sends '/reply' after it has received '/nsm/client/open'.

NSM API documentation says only: A response is REQUIRED as soon as the open operation has been completed.

So, as "ready", understand what you want ;) .

**Comment by Houston4444** [comment]
Just as indication, because you have done this feature very well. Another software would really needs a NSM implementation: Giada.

I saw that the author needs help for this: https://github.com/monocasual/giada/issues/232

You are maybe not interested by this software, but it is probably the best open source looper
available.

I would totally understand that you are not interested. I just pass the information to the relevant authorities ;)

**Comment by theGreatWhiteShark** [comment]
> I say "ready" for the moment the OSC server of the client (here Hydrogen) sends '/reply' after it has received '/nsm/client/open'.

Here you go. Now H2 sends the reply after being fully loaded.

> You are maybe not interested by this software, but it is probably the best open source looper
available.

Well, I'm definitely not lacking interest but time to keep up with the projects I'm already involved in. But I make a note for looking into the software. Thanks for the suggestion!

**Comment by grammoboy2** [comment]
Hydrogen now starts behind (!) the default non-session-manager gui. This is strange behavior and should be fixed.

**Comment by trebmuh** [comment]
> the solution should be extended to other session management systems like LADISH without a problem.

I wouldn't bother, LADISH is not developed anymore, barely maintained by packagers.

**Comment by trebmuh** [comment]
@theGreatWhiteShark : it seems that this one is full of conflicts now. Can you please rebased it on current master? @Houston4444 and myself are very interested to help out to get a proper support of NSM in Hydrogen. So far, the current NSM support is very broken and that is very unfortunate.

**Comment by theGreatWhiteShark** [comment]
@trebmuh nice to hear! I will do so tomorrow.

With the Jack-related bugs (hopefully) out of the way I will tackle this PR soon. But I will rebase #792 instead and close this one. The former supersedes this one. Originally I was not sure whether I was touching too much code and the PR would have a chance to be merged. That's why I split it into two.

**Comment by trebmuh** [comment]
OK, nice to read.
Please, let me know when something is ready for build & test, and I'll try to find time to do it so.

**Comment by theGreatWhiteShark** [comment]
superseded by #792

**Pull request closed without merging**
