### PR TITLE
Update hydrogen.pt_BR.ts

### PR DESCRIPTION
**Pull request by heit0r**
Hello, im heitor I'm <heitor@riseup.net> from the list. Am i doing it right? Thanks.

### CODE REVIEW

**Comment by trebmuh** [comment]
Hi @heit0r and thanks for the Pull Request (PR).
The PR method is fine. Well done.
But when looking at the changes your proposing, I can see that even if translated, there are still string which contain `type="unfinished"` which signals that _it's not done yet_ and as a consequence will not be update on the graphical user interface.
Please, remove those.

**Comment by trebmuh** [comment]
@heit0r : since you're keeping updating tis PR with some more commit (which is great), I'll wait before merging it to the main code (master).

Keep up the good work!

**Comment by heit0r** [comment]
@trebmuh Sorry to bother again. But i'm in doubt.

I traslated "song" to "canção", since "música" in pt_br means more like the whole music with full instruments and vocals than just a composition like we do on hydrogen. "Canção" also means music, but gets a closer meaning to "(musical) composition", that is what we do on hydrogen.

But, as far as i know, hydrogen is walking to be more than a drum machine, making it produce songs with full instruments. So should i keep "song" as music(música in pt_br)?

**Comment by trebmuh** [comment]
> @trebmuh Sorry to bother again. But i'm in doubt.

No worries at all, that's fine.


> I traslated "song" to "canção", since "música" in pt_br means more like the whole music with full instruments and vocals than just a composition like we do on hydrogen. "Canção" also means music, but gets a closer meaning to "(musical) composition", that is what we do on hydrogen.
> 
> But, as far as i know, hydrogen is walking to be more than a drum machine, making it produce songs with full instruments. So should i keep "song" as music(música in pt_br)?

I'm going to share with you the way I did in the French translation (which is my mother tongue).
_Song_ (EN) can translate in French to _morceau_, _chanson_, _musique_.

It looks like _chanson_ (FR) which the sense is "music + lyrics" is the equivalent of _canção_ (pt_BR) but I'm not sure that a _canção_ means the same in pt_BR. And _musique_ (FR) seems to be equivalent to _música_ (pt_BR).

_Morceau_ (FR) translates generally (not only in the music field) into "**a piece of**", or "**a part of**". And it is used quite a lot in the musical field in French.

I've quickly looked around the web and I see there is a "tracho" word in Portuguese (not sure if this is the same in pt_BR). Weither or not this word make sense in pt_BR, I'm leaving that to you. That was only to mention.

Hope that helps.

**Comment by heit0r** [comment]
Tracho hehehehe This word is most likely from european portuguese, i never heard about it. In pt_br we have "trecho", that means "a piece of", or "a part of", but isn't applied to music.

I think i'll leave it as "música", that means just music and will make sense to everyone in my language, that is the main objective here. Music is any harmonic and expressive combinations of sound under some variable rules, so, at the end, i think i didn't really needed to instigate this issue. ;p

But thank you so much @trebmuh for attention, anyway. Helped me to decide.

**Comment by heit0r** [comment]
I think it'll be nice to translate hydrogen manual too

**Comment by heit0r** [comment]
@trebmuh help, please. i need to know what to put on 2292 line. Fixed means something that was fixed up1 after was broken, but also means something 2firm, steady. In portuguese i have 1"consertado" and 2"fixo". What do i put here? Thanks!

**Comment by heit0r** [comment]
Sure, let us not mess things up heheheh I'll ping you here after i finish and review what i did. I'll stay tuned to know when you have an updated manual, and I'll translate it too if you guys think it's ok

**Comment by trebmuh** [comment]
> @trebmuh help, please. i need to know what to put on 2292 line. Fixed means something that was fixed up1 after was broken, but also means something 2firm, steady. In portuguese i have 1"consertado" and 2"fixo". What do i put here? Thanks!

@heit0r : this context isn't about something which was broken and is corrected. It is about a "fixed step" which means that all the steps are of the same (fixed) size. Fixed as "not variable", "all the same",...

I hope that helps you.

**Comment by heit0r** [comment]
@trebmuh help, please :)

Should i replicate the exactly same code of the sentences, or may i just translate the sentences without worry about the code aside?
Example:

<source>&lt;b&gt;PortAudio Driver&lt;/b&gt;&lt;br&gt;</source>
<translation>&lt;b&gt;Driver PortAudio&lt;/b&gt;&lt;br&gt;</translation>

OR can i just do:

<source>&lt;b&gt;PortAudio Driver&lt;/b&gt;&lt;br&gt;</source>
<translation>Driver PortAudio</translation>

Thank you!

**Comment by heit0r** [comment]
@trebmuh help, please :)

Should i replicate the exactly same code at the sentences, or may i just translate the sentences w/o worry about the code aside?

Example:
Can i do like this:
``<source>&lt;b&gt;CoreAudio Driver&lt;/b&gt;&lt;br&gt;</source>
        <translation>Driver CoreAudio</translation>``

Or should i do like this:

`<source>&lt;b&gt;CoreAudio Driver&lt;/b&gt;&lt;br&gt;</source>
        <translation>&lt;b&gt;Driver CoreAudio&lt;/b&gt;&lt;br&gt;</translation>``

?

Thanks again!

**Comment by heit0r** [comment]
@trebmuh help, please :)

Should i replicate the exactly same code at the sentences, or may i just translate the sentences w/o worry about the code aside?

Example:
Can i do like this:
``<source>&lt;b&gt;CoreAudio Driver&lt;/b&gt;&lt;br&gt;</source>
        <translation>Driver CoreAudio</translation>``

Or should i do like this:

``<source>&lt;b&gt;CoreAudio Driver&lt;/b&gt;&lt;br&gt;</source>
        <translation>&lt;b&gt;Driver CoreAudio&lt;/b&gt;&lt;br&gt;</translation>``

?

Thanks again!

**Comment by trebmuh** [comment]
> Should i replicate the exactly same code at the sentences, 

Yes

> or may i just translate the sentences w/o worry about the code aside?

No

> Example:
> Can i do like this:
> ``<source>&lt;b&gt;CoreAudio Driver&lt;/b&gt;&lt;br&gt;</source>
        <translation>Driver CoreAudio</translation>``

No

> Or should i do like this:
> ``<source>&lt;b&gt;CoreAudio Driver&lt;/b&gt;&lt;br&gt;</source>
        <translation>&lt;b&gt;Driver CoreAudio&lt;/b&gt;&lt;br&gt;</translation>``

Yes

**Comment by trebmuh** [comment]
@heit0r :

> Should i replicate the exactly same code at the sentences, 

Yes

> or may i just translate the sentences w/o worry about the code aside?

No

> Example:
> Can i do like this:
> ``<source>&lt;b&gt;CoreAudio Driver&lt;/b&gt;&lt;br&gt;</source>
        <translation>Driver CoreAudio</translation>``

No

> Or should i do like this:
> ``<source>&lt;b&gt;CoreAudio Driver&lt;/b&gt;&lt;br&gt;</source>
        <translation>&lt;b&gt;Driver CoreAudio&lt;/b&gt;&lt;br&gt;</translation>``

Yes

Hope that helps.

**Comment by trebmuh** [comment]
@heit0r : nice to see you're getting close the completeness!

I saw there is a mistake on line 595: `<translation&amp;Cancelar</translation>` is missing a `>` between `translation` and `&amp;`.

**Comment by heit0r** [comment]
Just finished the last line and also made the correction of 595 line. :) I would like to review my translation before i say it's really finished, but if you want to merge it to the code, feel free to do it. This translation can be updated later on? Because i think some phrases could break the space some dialog boxes. Much words in portuguese are larger than in english.

**Comment by trebmuh** [comment]
@heit0r : another missing `>` on line 770.

**Comment by trebmuh** [comment]
@heit0r : I've corrected 2 missing `>`. Please, be careful of those.

**Comment by heit0r** [comment]
Sure (y) I'm reviewing the whole code right now, but i think you did the main corrections. Thank you :) I'm just making small changes or putting some missing characters.

**Comment by trebmuh** [comment]
@heit0r : let me know when you think it's fine enough to be incorporated into the main code.

**Comment by heit0r** [comment]
@trebmuh I think now it's fine. Done some corrections and small changes. Thank you so much for your support, was a nice experience. :nerd_face:

**Comment by trebmuh** [comment]
@heit0r it is merged now.
Well done for the job!

By the way, what OS and version are you running?

**Comment by heit0r** [comment]
Was an very nice experience. It's great to feel part of something that you admire and believe like any free software initiative. I just would like to ask if you could sign me as Heitor Rocha :) I didn't realize that my last name was missing on my profile. I did it fast so i could work soon on the translation.

Yes, i can test a fresh copy of Hydrogen, that's why i was asking if i can update this translation afterwards. I would like see if things are working fine on my system. I'll keep checking my inbox :)

Thank you @trebmuh !

**Pull request merged**
