### PR TITLE
Fixes issue #332:  loading drumkit does not clean up previous drumkit

### PR DESCRIPTION
**Pull request by pvint**
Fixes the issue #332  where sometimes instruments got left behind when loading a new kit

### CODE REVIEW

**Comment by trebmuh** [comment]
Does look to be working for me. Please see my comment: https://github.com/hydrogen-music/hydrogen/issues/332#issuecomment-183781046

**Comment by pvint** [comment]
Hi @trebmuh 
Try it now - it's not heavily tested yet, but it seems to be working as desired.

@thijz  Maybe we can get you to test this too?

This update is regarding the change made to prompt for keeping or discarding instruments when loading a smaller kit #332

**Comment by trebmuh** [comment]
@pvint: I tried it quickly, and the patch doesn't want to apply here, saying:
```
patching file src/core/src/hydrogen.cpp
Hunk #2 FAILED at 2502.
1 out of 2 hunks FAILED
```
It might be because I've been testing too much thing and I'll be better to make a fresh clean with your patch, which I'll do on this week-end (as I'll not have access to internet duringthe next 4 or 5 days).
Talk to you then!

**Comment by trebmuh** [comment]
OK @pvint I got some time today and I did a fresh git clone ( https://github.com/hydrogen-music/hydrogen/commit/956fd11414815318aa4a0d7379ff1d368dc31d0b ) and apply this patch ( https://github.com/hydrogen-music/hydrogen/pull/338.patch ) and it does work as expected.

Congratulation, that is great!

**Comment by pvint** [comment]
Thanks for testing and for the feedback.

Busy tonight and for the next couple days, but I'll make the changes as discussed at #332 and then maybe ask for more testing.

Cheers!
Paul

**Comment by trebmuh** [comment]
All good !

**Comment by thijz** [comment]
@mauser : any reason this has not been merged yet ?

**Comment by pvint** [comment]
@thijz  I think I never got to preventing the new dialog box popping up when there are not extra instruments - I will check right now and if I can I will fix that up quickly.

**Comment by pvint** [comment]
I added a check to see if instruments that might be removed have notes and will now only ask the user if there are active notes (based on discussion at #332 ), and I believe that resolves any outstanding concerns.

Paul

**Comment by pvint** [comment]
Also improved (I think) the wording on the dialog that will get presented to the user when there are more instruments in the old kit than the one being loaded (and one or more of them has notes)
snapshot13

**Comment by trebmuh** [comment]
@pvint : I've been rebuilding Hydrogen from a fresh git clone (https://github.com/hydrogen-music/hydrogen/commit/d7dacfedf73ede1af24ddedf260cfce5ca77df18) + your patch (https://patch-diff.githubusercontent.com/raw/hydrogen-music/hydrogen/pull/338.patch ) + patch https://patch-diff.githubusercontent.com/raw/hydrogen-music/hydrogen/pull/360.patch (nothing relevant here, just for the sake of completeness) and it does look to be working as expected.

Congratz and thanks!

@mauser : it looks to me that this is ready for being merged.

**Comment by pvint** [comment]
Thanks for the feedback @trebmuh 

I was starting to make the change to "keep" rather than "save", but then I thought of the translations... the buttons /i used are standard buttons and I presume they will already translate correctly (not tested!), whereas if I make a new "Keep" button we would need to translate.... maybe not worth the trouble?

I don't mind making the change, but I thought I would mention the translation first.

Paul

**Comment by trebmuh** [comment]
@pvint: just my opinion here, as a translator, I don't care much about adding one or two lines (even 50) as long that this can make more sense and improve the user comprehension and experience.
(You are right when presuming that the translation are done automatically in this case - at least, that the case for the French translation)

That said, as an user, I would be a bit confused reading "save" in this case since "save" is usually saving something "hard on the disk" where here, it's not about saving "hard" but "keeping" something instead of discarding it.

This is why my opinion is to go with "keep" and "discard" on this case.
Hope that help,
Olivier

**Comment by pvint** [comment]
@trebmuh, I'm convinced - I will try to make the change tonight. :)

**Comment by pvint** [comment]
Changed as discussed - thanks for the input @trebmuh!

snapshot19

**Comment by trebmuh** [comment]
:+1: thanks for the change @pvint , happy to have been useful here!

**Comment by trebmuh** [comment]
@mauser: this one sounds to be ready for merging into master.

**Comment by mauser** [comment]
Great! I'm going to test it in the next days..

**Comment by trebmuh** [comment]
Sweet :)

**Comment by mauser** [comment]
Thanks for the pull request, it's merged now!

**Comment by pvint** [comment]
Awesome - thanks @mauser  and thanks for all the testing and input @trebmuh & @thijz !

**Comment by trebmuh** [comment]
Sweet. Added to : https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-0.9.7#all-platforms

Thanks @pvint @mauser and @thijz .

**Pull request merged**
