### PR TITLE
Add simple GUI crash reporter

### PR DESCRIPTION
**Pull request by cme**
Simple crash reporter GUI, which gives options to examine the log, report bug, etc, and reports any information known about the context that caused the crash (eg. LADSP plugins). This addresses #1592 .

image

Currently this is a draft as it could use some polishing, and also because it's shown some errors I hadn't noticed before in some fairly common circumstances, so holding off adding until I investigate some of those.

### CODE REVIEW

**Comment by sirjohndfox** [comment]
Gday. When trying to compile the master branch on Debian stable with gcc v8.3. I get this error

hydrogen/src/gui/src/Reporter.cpp:179:23: error: comparison between distinct pointer types ‘QPushButton*’ and ‘QAbstractButton*’ lacks a cast
    if ( pLogButton == pPushed ) {
                       ^~~~~~~
hydrogen/src/gui/src/Reporter.cpp:182:27: error: comparison between distinct pointer types ‘QAbstractButton*’ and ‘QPushButton*’ lacks a cast
    } else if ( pPushed == pIssuesButton ) {
                           ^~~~~~~~~~~~~
                           
  Then @theGreatWhiteShark added a cast (i was trying to test one of his pull requests) and I got the error:
  hydrogen/src/gui/src/Reporter.cpp: In member function ‘void Reporter::on_finished(int, QProcess::ExitStatus)’: /home/john/SOFTWARE/hydrogen/src/gui/src/Reporter.cpp:179:49: error: invalid static_cast from type ‘QPushButton*’ to type ‘QAbstractButton*’ if ( static_cast<QAbstractButton*>(pLogButton) == pPushed ) { ^ /home/john/SOFTWARE/hydrogen/src/gui/src/Reporter.cpp:183:57: error: invalid static_cast from type ‘QPushButton*’ to type ‘QAbstractButton*’ else if ( static_cast<QAbstractButton*>(pIssuesButton) == pPushed ) {

**Comment by cme** [comment]
Ooh this is weird. That should he a perfectly valid upcast as `QPushButton` inherits `QAbstractButton`.

Did that file report any warnings before the error?

Have you any extra compile flags (like, say, `-Werror`)

**Comment by cme** [comment]
> Gday. When trying to compile the master branch on Debian stable with gcc v8.3. I get this error
> 
> hydrogen/src/gui/src/Reporter.cpp:179:23: error: comparison between distinct pointer types ‘QPushButton*’ and ‘QAbstractButton*’ lacks a cast if ( pLogButton == pPushed ) { ^~~~~~~ hydrogen/src/gui/src/Reporter.cpp:182:27: error: comparison between distinct pointer types ‘QAbstractButton*’ and ‘QPushButton*’ lacks a cast } else if ( pPushed == pIssuesButton ) { ^~~~~~~~~~~~~

Ah, it looks like I missed including QtWidgets explicitly. This can get missed in testing because the CMake setup has pre-compiled headers to speed up building, so it masks such an error if pre-compiled headers aren't used

(By the way, which version of CMake do you have?)

I'll merge the fix as soon as the build checks are complete but if you're super-keen you could try #1641

**Comment by sirjohndfox** [comment]
Cheers for looking into this.  I've cmake version 3.13.4.  I'll have a go at compiling 1641 presently.

**Comment by sirjohndfox** [comment]
Compiles no worries!
@theGreatWhiteShark  This fix means your adding of cast wasn't necessary - I bodged the corrected files back into #1640 locally and it compiled fine!  I'm not sure of the message etiquette here. I realise I might've cross-posted a bit - is there anything I need to close?

**Comment by cme** [comment]
> Cheers for looking into this. I've cmake version 3.13.4. I'll have a go at compiling 1641 presently.

Ah that explains it, 3.13 is too early for pre-compiled header support.

Fix is on master now.

**Comment by theGreatWhiteShark** [comment]
> I realise I might've cross-posted a bit - is there anything I need to close?

Nope. AFAICS everything is fine

**Pull request merged**
