### PR TITLE
Allow more space for translated strings

### PR DESCRIPTION
**Pull request by pvint**
Improvements for issue #397

### CODE REVIEW

**Comment by mauser** [comment]
Thanks a lot, merged!

**Comment by pvint** [comment]
My pleasure. ))

**Comment by trebmuh** [comment]
@pvint : thanks Paul !

**Comment by trebmuh** [comment]
Just to be sure, is it normal/expected that this commit contains some stuff related to raptor? I really don't know about it but it sounds suspicious to me so I wanted to get your eyes on it @pvint and @mauser . (Sorry for the noise if so.)

**Comment by pvint** [comment]
@trebmuh  The raptor stuff was just stuff I accidentally pushed to this branch and then subsequently removed, so no worries.  Good to bring it up though. :)

**Comment by trebmuh** [comment]
@pvint: ok thanks. I was finding it strange when looking at this patch ( https://patch-diff.githubusercontent.com/raw/hydrogen-music/hydrogen/pull/431.patch ) that some RAPTOR stuff were still added (with a + at the beginning of the line). Thanks for answering that quick!

**Comment by pvint** [comment]
Wow, I knew that was confusing, but the patch REALLY makes it look like other files were changed!

I see what happened now though - those changes are changes that have been pulled since I last updated this branch, but I also had the changes in this branch. (speaking of confusing, I think that statement is confusing!). Summary: Those changes for raptor were added to hydrogen/master a while ago in separate pulls. I'm getting better at keeping my branches clean, but I still could improve ;)

I think this will make it more clear than my explanation :) :
https://github.com/hydrogen-music/hydrogen/pull/431/files

Cheers!
Paul

**Comment by trebmuh** [comment]
Thanks you very much for your explanation. Despite of the confusingness, I think I've got it now ! Thanks to this, I now know that I need to look at the files changed rather that the .patch for a better understanding :)

You have been really great and kind here in teaching me so. Kudos to you !

**Pull request merged**
