### PR TITLE
Velocity automation

### PR DESCRIPTION
**Pull request by elpescado**
# Overview

This branch allows users to adjust velocity of played notes via a timeline called "automation path":
screenshot
[audio](https://soundcloud.com/el-pescado/ap-demo/s-Vyy16)

That path allows to create more complex songs using fewer patterns. It works especially nice with multi-layered drumkits.
# Features
- Support for built in playback (sampler)
- Support for MIDI export
- Saving and loading songs
- Full undo&redo support
- Unit tests
# Prerequisites

This branch makes conserative use of C++11 features so it needs C++ support enabled (see pull request #263).
# Regressions

This branch should be backwards compatible. Songs created before will get constant velocity adjustment=1.0, which means note velocities will remain unchanged.

# How to test

* Check whether it's possible to add points to velocity automation path, move and delete them
* Check whether velocity is adjusted in playback in Song mode
* Check whether notes are played with their nominal velocity in Pattern mode
* Check whether note velocity is adjusted according to velocity path in exported audio file
* Check whether note velocity is adjusted according to velocity path in exported MIDI file
* Check whether after saving song with velocity automation path it's possible to load that song file, and velocity automation is correctly loaded

### CODE REVIEW

**Comment by trebmuh** [comment]
This looks awesome ! I'll be trying to test it as soon as possible.

Does the velocity changes in the pattern part are still working ? How do you handle those ?

**Comment by elpescado** [comment]
Yes, it's still working. Final note velocity is computed as note own velocity * velocity adjustment from timeline * humanize factor. Range for velocity adjustment is [0, 1.5].

**Comment by trebmuh** [comment]
Hi @elpescado , I've been trying to build hydrogen from a fresh git clone (  https://github.com/hydrogen-music/hydrogen/commit/956fd11414815318aa4a0d7379ff1d368dc31d0b ) with the addition of the 2 patches : https://patch-diff.githubusercontent.com/raw/hydrogen-music/hydrogen/pull/356.patch and https://patch-diff.githubusercontent.com/raw/hydrogen-music/hydrogen/pull/263.patch
but it fails building.
What would be your suggestion?

**Comment by elpescado** [comment]
What errors are you getting?

One thing I can think of is that this branch requires C++11 support from compiler. I created pull request which enables it, but it hasn't been merged yet.

**Comment by elpescado** [comment]
By the way, what OS/distro and which version of gcc/clang are you using? I have successfully built this branch on Debian unstable (with #263 applied before).

**Comment by thijz** [comment]
probably off-topic, but i'll ask it any way ;-)
any chance of linking this overall instrument velocity to a midi controller ?
it would be really great if you could control the velocity live !
(you can now more or less do this using the instrument volume, but this does not have the same effect a changing the velocity)

**Comment by elpescado** [comment]
Any feedback?

**Comment by trebmuh** [comment]
Hi @elpescado : trying to build hydrogen from today (https://github.com/hydrogen-music/hydrogen/commit/d7dacfedf73ede1af24ddedf260cfce5ca77df18) + your patch: https://patch-diff.githubusercontent.com/raw/hydrogen-music/hydrogen/pull/356.patch

I've got the following when trying to apply the patch:
```
patching file src/core/include/hydrogen/basics/automation_path.h
patching file src/core/src/basics/automation_path.cpp
patching file src/tests/automation_path_test.cpp
patching file src/core/include/hydrogen/basics/song.h
Hunk #2 FAILED at 190.
Hunk #3 FAILED at 210.
2 out of 3 hunks FAILED
patching file src/core/src/basics/song.cpp
Hunk #2 FAILED at 77.
Hunk #3 succeeded at 104 (offset -5 lines).
1 out of 3 hunks FAILED
patching file src/core/include/hydrogen/basics/automation_path.h
patching file src/core/src/basics/automation_path.cpp
patching file src/tests/automation_path_test.cpp
patching file src/core/include/hydrogen/automation_path_serializer.h
patching file src/core/src/automation_path_serializer.cpp
patching file src/tests/automation_path_serializer_test.cpp
patching file src/core/src/hydrogen.cpp
Hunk #2 succeeded at 462 (offset -2 lines).
Hunk #3 succeeded at 491 (offset -2 lines).
patching file src/core/src/smf/smf.cpp
Hunk #2 FAILED at 238.
Hunk #3 FAILED at 264.
2 out of 3 hunks FAILED
patching file src/core/src/basics/song.cpp
Hunk #2 FAILED at 996.
1 out of 2 hunks FAILED
patching file src/core/src/local_file_mgr.cpp
Hunk #2 succeeded at 1570 (offset 34 lines).
patching file src/core/include/hydrogen/basics/automation_path.h
patching file src/core/src/basics/automation_path.cpp
patching file src/tests/automation_path_test.cpp
patching file src/gui/src/widgets/AutomationPathView.cpp
patching file src/gui/src/widgets/AutomationPathView.h
patching file src/gui/src/SongEditor/SongEditorPanel.cpp
patching file src/gui/src/SongEditor/SongEditorPanel.h
patching file src/gui/src/SongEditor/SongEditorPanel.cpp
patching file src/gui/src/SongEditor/SongEditorPanel.cpp
patching file src/gui/src/widgets/AutomationPathView.cpp
patching file src/core/src/basics/song.cpp
Hunk #1 FAILED at 84.
1 out of 1 hunk FAILED
patching file src/core/include/hydrogen/basics/automation_path.h
patching file src/core/src/basics/automation_path.cpp
patching file src/gui/src/widgets/AutomationPathView.cpp
patching file src/tests/automation_path_test.cpp
patching file src/gui/src/SongEditor/SongEditorPanel.cpp
patching file src/gui/src/SongEditor/SongEditorPanel.h
patching file src/gui/src/widgets/AutomationPathView.cpp
patching file src/gui/src/widgets/AutomationPathView.h
patching file src/core/src/hydrogen.cpp
Hunk #1 succeeded at 469 (offset -2 lines).
patching file src/core/include/hydrogen/basics/automation_path.h
patching file src/core/src/basics/automation_path.cpp
patching file src/tests/automation_path_test.cpp
patching file src/gui/src/SongEditor/SongEditorPanel.cpp
Hunk #2 FAILED at 611.
1 out of 2 hunks FAILED
patching file src/gui/src/SongEditor/SongEditorPanel.h
patching file src/gui/src/UndoActions.h
patching file src/gui/src/widgets/AutomationPathView.cpp
patching file src/gui/src/widgets/AutomationPathView.h
patching file src/gui/src/widgets/AutomationPathView.cpp
patching file src/gui/src/widgets/AutomationPathView.h
patching file src/gui/src/SongEditor/SongEditorPanel.cpp
Hunk #1 FAILED at 623.
1 out of 1 hunk FAILED
patching file src/gui/src/UndoActions.h
patching file src/gui/src/SongEditor/SongEditorPanel.cpp
Hunk #2 FAILED at 628.
1 out of 2 hunks FAILED
patching file src/gui/src/SongEditor/SongEditorPanel.h
patching file src/gui/src/UndoActions.h
patching file src/gui/src/widgets/AutomationPathView.cpp
patching file src/gui/src/widgets/AutomationPathView.h
patching file src/core/src/basics/automation_path.cpp
patching file src/core/include/hydrogen/automation_path_serializer.h
patching file src/core/include/hydrogen/basics/automation_path.h
patching file src/core/src/automation_path_serializer.cpp
patching file src/core/src/basics/automation_path.cpp
patching file src/gui/src/widgets/AutomationPathView.cpp
patching file src/gui/src/widgets/AutomationPathView.h
patching file src/tests/automation_path_serializer_test.cpp
patching file src/tests/automation_path_test.cpp
```
Also, please note that github is saying in this thread that "This branch has conflicts that must be resolved".

Same than with https://github.com/hydrogen-music/hydrogen/pull/358 , I'd like to help testing this feature which looks definitely to be another great addition to Hydrogen from my POV.

Hope that helps

PS: ditto here: I reckon that patching with #263 is not needed anymore since it's been merged to Master back in March.

**Comment by elpescado** [comment]
I have to merge latest master, unfortunately I'm bit busy right now. In the meantime, you could just checkout my branch directly.

**Comment by trebmuh** [comment]
Trying to build from your repo/branch, the build is failing with the following:
```
[  2%] Building CXX object src/core/CMakeFiles/hydrogen-core-0.9.7.dir/src/basics/automation_path.cpp.o
cd /tmp/buildd/hydrogen-elpescado-autopath-0.9.7/obj-x86_64-linux-gnu/src/core && /usr/bin/g++    -O2 -fno-implement-inlines -g  -I/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/include -I/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/include -I/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/obj-x86_64-linux-gnu/src/core/include -I/usr/include/qt4/QtDesigner -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4/QtScriptTools -I/usr/include/qt4/QtDBus -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtHelp -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtTest -I/usr/include/qt4/QtScript -I/usr/include/qt4/QtSvg -I/usr/include/qt4/Qt3Support -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore -I/usr/share/qt4/mkspecs/default -I/usr/include/qt4    -o CMakeFiles/hydrogen-core-0.9.7.dir/src/basics/automation_path.cpp.o -c /tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp: In member function 'float H2Core::AutomationPath::get_value(float) const':
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:51:7: error: 'f' does not name a type
  auto f = _points.begin();
       ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:52:10: error: 'f' was not declared in this scope
  if(x <= f->first)
          ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:55:7: error: 'l' does not name a type
  auto l = _points.rbegin();
       ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:56:10: error: 'l' was not declared in this scope
  if(x >= l->first)
          ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:59:7: error: 'i' does not name a type
  auto i = _points.lower_bound(x);
       ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:60:7: error: 'p1' does not name a type
  auto p1 = *i;
       ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:61:7: error: 'p0' does not name a type
  auto p0 = *(--i);
       ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:62:13: error: 'p0' was not declared in this scope
  float x1 = p0.first;
             ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:64:13: error: 'p1' was not declared in this scope
  float x2 = p1.first;
             ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp: In function 'std::ostream& H2Core::operator<<(std::ostream&, const H2Core::AutomationPath&)':
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:107:12: error: 'i' does not name a type
  for (auto i = p.begin(); i != p.end(); ++i) {
            ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:107:27: error: expected ';' before 'i'
  for (auto i = p.begin(); i != p.end(); ++i) {
                           ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:107:27: error: 'i' was not declared in this scope
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp: In member function 'H2Core::AutomationPath::iterator H2Core::AutomationPath::find(float)':
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:128:7: error: 'i' does not name a type
  auto i = _points.lower_bound(x);
       ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:130:6: error: 'i' was not declared in this scope
  if (i != _points.end()) {
      ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:135:4: error: 'i' was not declared in this scope
  --i;
    ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp: In member function 'H2Core::AutomationPath::iterator H2Core::AutomationPath::move(H2Core::AutomationPath::iterator&, float, float)':
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:152:7: error: 'rv' does not name a type
  auto rv = _points.insert(std::make_pair(x,y));
       ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:153:9: error: 'rv' was not declared in this scope
  return rv.first;
         ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp: In member function 'void H2Core::AutomationPath::remove_point(float)':
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:163:7: error: 'it' does not name a type
  auto it = find(x);
       ^
/tmp/buildd/hydrogen-elpescado-autopath-0.9.7/src/core/src/basics/automation_path.cpp:164:6: error: 'it' was not declared in this scope
  if (it != _points.end()) {
      ^
src/core/CMakeFiles/hydrogen-core-0.9.7.dir/build.make:149: recipe for target 'src/core/CMakeFiles/hydrogen-core-0.9.7.dir/src/basics/automation_path.cpp.o' failed
make[3]: *** [src/core/CMakeFiles/hydrogen-core-0.9.7.dir/src/basics/automation_path.cpp.o] Error 1
```
Hope that helps

**Comment by elpescado** [comment]
I have updated my branch so that it should merge cleanly.

**Comment by mauser** [comment]
Hi! 

I've spend some time today playing around with the pull request. One thing i've encountered is that the "automation area" is not bounded above - you can move the automation points out of that area. 

Have you thought about creating a multi-purpose automation tool for all note properties? I suppose it would be nice if one could create "swing" parts by addind lead/lag just to some sections of the song - without changing the patterns. 

Another thing: We need a possibility to enable/disable the song editor gui elements in the future. A user should be able to choose if he wants to see the playback track, the timeline, an automation path (or maybe even multiple automation path views?) or none of them.. Maybe with small icons to the left of the song editor scroll bar? Just a general thought, not implying that this should be done in this pull request..

feedback

**Comment by mauser** [comment]
Sorry, totally forgot: The automation path is a great idea :) And i like the look of it..

**Comment by pvint** [comment]
+1 - This is a really great idea!

**Comment by elpescado** [comment]
Hi,

Thanks for taking the time to test my branch. I'll take a look at the bug with upper boundary.

I see this feature as a starting point - the goal would be automating more aspects of a song. The next step that I have planned was adding automation to controls that could be adjusted via MIDI CCs (instrument volumes, FX levels etc). I have started working on this but hadn't time to finish it yet. Automating other note properties sounds like a good candidate for automating too. Thanks for suggesting that!

As for the GUI showing/hiding GUI elements in main window. I think adding "View" menu would be straightforward first step to solving this. Then I thought that maybe replacing "Mixer" and "Instrument Rack" buttons with icons and adding additional icons for timeline, playback and automation would be logical, as that's the pace where user can show/hide UI elements.

**Comment by elpescado** [comment]
Hi,

I've finally found some free time. I have merged current master branch, so this pull request should merge cleanly, and I've fixed bug that allowed to add points outside valid area. I tweaked automation path widget style a bit.

**Comment by elpescado** [comment]
Hi,

I'd appreciate any help with testing this feature:)

**Comment by trebmuh** [comment]
Hi @elpescado ,
I've been building from your branch and testing it and, so far, everything going well! Really nice feature. Thanks.
I hope @mauser will commit this to master soon :)
If you need some special tests, please let me know.

**Comment by trebmuh** [comment]
@elpescado @0-wiz-0 : I'm not too sure to understand what happened here. There looks to be just a merge with current master branch, but I wonder if you reckon it would need another testing round. Please, advise.

**Comment by elpescado** [comment]
Hi, I merged current master to keep this branch fresh, so I don't think it needs more testing.

**Comment by trebmuh** [comment]
Ok, thanks.

@mauser : what do you think about merging it to master (only being curious here) ?

**Comment by mauser** [comment]
Hi! 

Yes, i can merge this soon! (No time to test at this moment). It would be great if a label/description could be added to the left of the automation path (or a combo box later) which tells the users what this blue line is all about.

**Comment by trebmuh** [comment]
@elpescado : would you be able to add a "volume automation" label or something around this line?

**Comment by pvint** [comment]
I've been following this for a while, and I will admit that I while haven't tried it yet, this sounds really great. I will really try to test this out soon.

**Comment by elpescado** [comment]
Adding label is a great idea. I haven't thought about it, for me it was obvious, but for first-time user, showing just blue line must indeed be confusing.

**Comment by elpescado** [comment]
Hi, I added label (in form of LCDCombo) to velocity path view and fixed bug that caused crash when removing points in path.

**Comment by elpescado** [comment]
Hi,

Is there anything that is blocking this pull request? In case anyone is interested in testing this feature, I have added "How to test" section in PR with test scenarios that came to my mind.

**Comment by mauser** [comment]
Hi,

tried to reach you via mail this week, but i suppose sth. went wrong if you haven't received it. I was busy for some time but will work on this one next week, maybe we can also put a first beta1-version out then...

**Comment by mauser** [comment]
... and of course it would be much appreciated if someone wants to test this feature :)

**Comment by mauser** [comment]
Thanks @elpescado , the branch is merged now! I will propably make the automation area hideable via the "View" menu or sth. similiar

**Comment by trebmuh** [comment]
Nice to get it in master !

@elpescado @mauser : it looks I found a little bug, see: http://download.tuxfamily.org/librazik/volatile/bug-hydrogen-velocity-automation.mp4

**Comment by trebmuh** [comment]
Nice to get it in master ! Added here: https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-1.0

@elpescado @mauser : it looks I found a little bug, see: http://download.tuxfamily.org/librazik/volatile/bug-hydrogen-velocity-automation.mp4

**Comment by elpescado** [comment]
Whoops, that's embarassing:| I'll have to look into this.

**Comment by elpescado** [comment]
Hi,

I have managed to find some time today. Fortunately, the "dots from outer space" bug turned out to be easy one - being able to drag points outside left margin was beacuse of comparing signed and unsigned integers. I have fixed it in my branch, elpescado:bugfix/automation

I'll look into "dots eating dots" bug when I find some more time. I'll create a pull request then.

**Comment by trebmuh** [comment]
Hi @elpescado : thanks for having tackled the "dots from outer space". That was the one I referred. The "dots eating dots", well, ... I thought it was a feature ! I'll try to find sometime soon to rebuild hydrogen with your fix and will report back to you.
Cheers.

**Comment by elpescado** [comment]
I am confused now;) Dots-eating-dots were by design, but after your report I thought it wasn't fortunate design. I have to think about it more... In the meantime, I have created pull request for the first bugfix.

**Comment by trebmuh** [comment]
> I am confused now;) Dots-eating-dots were by design, but after your report I thought it wasn't fortunate design. I have to think about it more...

So it's fine. I think it is a good feature. No need to change it.

> In the meantime, I have created pull request for the first bugfix.

I'll be rebuilding hydrogen with adding this patch and will report back to you after.

Thanks!

**Comment by trebmuh** [comment]
Rebuilt and tested. All good, thanks @elpescado !

**Pull request merged**
