### PR TITLE
Tweaked README.md

### PR DESCRIPTION
**Pull request by luzpaz**
Added several sections and utilized markdown formatting. Also added Repology badges to track the version number of Hydrogen the different downstream packaging repos are carrying.

Todo: Please add a LICENSE file and link to it from the end of the README.md file

### CODE REVIEW

**Comment by luzpaz** [comment]
Preview: https://github.com/luzpaz/hydrogen/blob/README-tweak/README.md

**Comment by trebmuh** [comment]
LGTM

> Todo: Please add a LICENSE file and link to it from the end of the README.md file

See the COPYING file.

**Comment by luzpaz** [comment]
@trebmuh Perhaps consider changing this to LICENSE.txt ?

**Comment by trebmuh** [comment]
@mauser what do you think?

**Comment by mauser** [comment]
> @trebmuh Perhaps consider changing this to LICENSE.txt ?

Hi! 

COPYING is one of the default names for a GPL license file. 

About the pull request: in my optinion the Logo is a little bit too much there, i think i might remove that later. What to others think about the logo?

**Comment by theGreatWhiteShark** [comment]
I would go even further and add a screenshot of the main window, like an updated version of the first one in the [screenshot galery](http://hydrogen-music.org/images/screenshots/main-window.png), instead of the logo. 

It makes clear right from the start that H2 is not a mere plugin or command line tool but comes with a (rather sophisticated) GUI. 

For bigger projects it's actually quite common to add a picture or logo - in case the project can not easily summarized with a single screenshot - at the very beginning. (The OpenDesign team of Mozilla puts a lot of emphasis on that a good README should consist Name - Picture - short abstract - concise feature list - installation guide - more detailed description + references. In that order. So either way would be good practice)

**Comment by luzpaz** [comment]
Le me know what y'all decide to do and I'll be happy to revise based on that.

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
bump

**Comment by luzpaz** [comment]
Please check the Preview again: https://github.com/hydrogen-music/hydrogen/pull/770#issuecomment-533169104

**Comment by luzpaz** [comment]
any follow-ups on this ?

**Comment by mauser** [comment]
Thanks a lot for your work, merged!

**Pull request merged**
