### PR TITLE
#496 raptor.h issue. Possible fix.

### PR DESCRIPTION
**Pull request by vladimir-kirillovskiy**
I've removed changes that was made previously for issues #194, #342 and #395.

It seems that the problem was not with the raptor includes, but with LRDF. So I removed lines in CMakeFiles for raptor and corrected a line for LRDF. 

It works for me on Arch Linux.

### CODE REVIEW

**Comment by pvint** [comment]
Compiles fine in both Gentoo and Ubuntu! :)

**Comment by vladimir-kirillovskiy** [comment]
I've also noticed spelling error on variable name. I added it on this pull request  as it is in the same file.

@pvint could you re-test it?) Thank you!

**Comment by pvint** [comment]
Still compiles fine with Gentoo - I cannot test at the moment with Ubuntu.

Side note: Good catch on the typo there! Generally it's better to have unrelated changes in a separate PR, but if not one else minds, I'd say to leave this one here.

Since it might affect compiling on a Mac, it would be good if someone with a Mac could verify this works OK.

Thanks!
Paul

**Comment by mauser** [comment]
@pvint : Hydrogen now uses Travis CI, so every new commit to our repo triggers a build on Ubuntu and Mac OS X. The last build on OS X has failed, but it looked more like a timeout problem. I've restarted the build..

**Comment by pvint** [comment]
@mauser  Awesome - thanks for the info. I saw that but didn't have time to look into it. :)

**Comment by mauser** [comment]
@schivmeister : Ray, could you re-test this issue on your system?

**Comment by mauser** [comment]
Hi! 

I've merged this pull request now, it compiled on all system which i've tested so far..

**Comment by schivmeister** [comment]
@mauser Really sorry I failed to respond and act again in time, and thanks for testing it yourselves. I will try to attend to this soon on Arch Linux.

**Comment by mauser** [comment]
@schivmeister No problem, just mention it if there is an issue!

**Comment by simonvanderveldt** [comment]
> Compiles fine in both Gentoo and Ubuntu! :)

@pvint Bit of a random question, but which ebuild are you using for this? Or are you compiling from source?
Asking because the current ebuild in the gentoo tree still has this comment https://github.com/gentoo/gentoo/blob/master/media-sound/hydrogen/hydrogen-0.9.5-r1.ebuild#L39 about issues with finding the raptor2 headers.
Would this PR fix those issues?

**Pull request merged**
