### PR TITLE
Convert dialog box layouts to QLayout to accommodate i18n

### PR DESCRIPTION
**Pull request by cme**
To address #1207.

AudioFileBrowser so far, others to follow.

### CODE REVIEW

**Comment by trebmuh** [comment]
Please ping me when this PR is ready if you need a test.

**Comment by cme** [comment]
> Please ping me when this PR is ready if this needs a test.

Done, let me know if any issues :)

**Comment by cme** [comment]
I've tested this out with the French translation (also found a spurious '>' in `hydrogen_fr.ts` that broke things on macOS but seemed mysteriously to work on Linux) and it looks okay to me. I shall merge to master, if you spot anything else shout! Thanks! :)

**Comment by trebmuh** [comment]
Thank you very much.
I can confirm that all is fine with the French translation (rebuild from aa738c3)

**Pull request merged**
