### PR TITLE
Hydrogen Manual; Export Audio Function - Hydrogen V 1.0.1 Windows 7

### PR DESCRIPTION
**Pull request by YungPhil**
Hi -  small suggestion for the Manual - Hydrogen has two stated audio Export options 

1. export a song to a single stereo audio wav track 
2. export each instrument to individual tracks.

Option 2 is fine with a small number of instruments but you may want a combination of the two functions.

There is a 3rd workaround option -
It is possible to use Option 1 to export a selection of instruments e.g 
in a song where drums bass and instruments have been used -
 to export drums only as a mixed track, Mute all other instruments on the Mixer and Export song as a stereo track, This give a drum track.
To export bass only, select Solo for the bass track and export Song. Same for other instruments.
This gives separate wav files e.g. a stereo drum track and bass/instrument tracks for importing into a DAW such as Audacity. I've used this several times now.

### CODE REVIEW

**Comment by trebmuh** [comment]
@YungPhil : I'm a bit confused here. Is that a question or is that a pull request?

**Comment by YungPhil** [comment]
Hi It was a hopefully useful suggestion for inclusion in the manual.
Regards Phil
------ Original Message ------

**Comment by trebmuh** [comment]
I'm still confused @YungPhil .

- first, this isn't the repo for the documentation (which can be [found here](https://github.com/hydrogen-music/documentation))
- you made a PR here, which is targetting an old version of Hydrogen
- this PR is having conflicting files (see above)

Please, clarify.

**Comment by mauser** [comment]
@YungPhil: I'm going to close this pull request. Please create a ticket at the documentation repository (as @trebmuh  already pointed out).

**Pull request closed without merging**
