### PR TITLE
Make the hihat instrument a group one

### PR DESCRIPTION
**Pull request by blablack**
Make the hihat instrument a group one - this allowed for different drum trigger to have their own hihat group.
For v-drum with edge/head hi-hat this allows to have a different set of samples for the pressure.

It fixes this bug: https://github.com/hydrogen-music/hydrogen/issues/246

### CODE REVIEW

**Comment by mauser** [comment]
Hi @blablack ,

About  data/img/gray/instrumentEditor/instrumentTab_new.png: As already mentioned via mail, would it be possible to place the control items in one row to save screen height? It would be great if those changes would not affect the minimum screen height of this widget.

**Comment by blablack** [comment]
Hi @mauser ,

Control items are now on line - i modified the minimum size of the widget as well.
Let me know if there is anything else you would like me to correct.

**Comment by mauser** [comment]
Perfect! It's merged now. For reference: Documentation can be found in #295 until it is merged into the manual.

**Comment by trebmuh** [comment]
(as already written in https://github.com/hydrogen-music/hydrogen/issues/295)
I did put a note of this in the next release note : https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-0.9.7

**Pull request merged**
