### PR TITLE
Apply driver pref changes before restart output

### PR DESCRIPTION
**Pull request by cme**
Implemented proposed changes to Preferences dialog box for audio driver options to address #883, applying changes before restarting driver.

### CODE REVIEW

**Comment by theGreatWhiteShark** [comment]
I like it.

But two things confuse me (which probably already have been present beforehand).
1. The actual sample rate and buffer size of the Jack server is not reflected by the displayed numbers. (The latter we could also display grey to indicate that they represent something static)
2. The choice of the Auto driver is not reflected after restarting.

But we could of course merge this PR and handle/discuss the things above in a separate one.

**Comment by theGreatWhiteShark** [comment]
@cme can we merge this?

**Comment by cme** [comment]
> @cme can we merge this?

Yep.

Today's lesson: resolving conflicts in `.ui` files is not my favourite thing ever.

**Review by theGreatWhiteShark — APPROVED** [review]

**Comment by theGreatWhiteShark** [comment]
> Today's lesson: resolving conflicts in .ui files is not my favourite thing ever.

Yeah. When I first saw QtDesigner I thought tweaking the GUI will be so much easier. But the devil is in the detail and it is not nearly as simple as I thought it to be.

**Pull request merged**
