### PR TITLE
Allow user to select high dpi scaling rounding policy

### PR DESCRIPTION
**Pull request by cme**
This addresses #914 by allowing the user to choose the rounding mode.

Not yet tested on Windows as my MXE is in the process of rebuilding.

### CODE REVIEW

**Comment by mauser** [comment]
Thanks a lot, merged!

**Comment by cme** [comment]
I should note that I haven't actually tested this on Windows -- the Appveyor build uses Qt 5.12 (which at least let me test the fallback behaviour!) but I haven't had time to get a working mxe + windows build going locally to test.

**Comment by cme** [comment]
Finally managed to pull together a working mxe build from mac os -> windows again to test this, and found that it doesn't actually work.

The issue is the call to set the scaling factor has to happen before initialisation of the QApplication object. However, there's circular ordering dependencies that mean there's no valid ordering that allows us to use a preference so early:

 * set rounding policy must precede QApplication initialisation
 * QApplication initialisation must precede Filesystem::bootstrap()
 * Filesystem::bootstrap must precede preferences loading
 * Preferences loading must precede setting rounding policy

So it looks like making this actually *work* might need some substantial refactoring to break apart initialisation dependencies. I'll continue to take a deeper look.

**Comment by mauser** [comment]
We could also add the rounding policy as a command line param. This is a bit tricky for the windows users, but it would be a workaround for the dependency problem. What i don't like about this solution is that the command line params are more or less "invisible" for a standard windows user. The UI settings in the preferences dialog are easier to find.

**Comment by cme** [comment]
Having gone through the dependencies, it looks like the cycle can be broken by changing Filesystem::bootstrap() to act in two stages (which seems reasonable given the bootstrap nature of the method). The only dependency it has on QApplication is for sys_data_path.

I have a working version which I'm going to test on Windows and Linux shortly, which basically:

  * delays pQApp initialisation until later in main() in the GUI app
  * Filesystem::bootstrap() checks QCoreApplication::isStartingUp(). If so, it skips setting sys_data_path, but sets other paths (so that Preferences can be loaded). A null string value is set in __sys_data_path.
  * adds a second call to Filesystem::bootstrap() in main(), after pQApp initialisation, to allow the bootstrap to complete.
  * Filesystem::sys_data_path() asserts that it isn't returning the dummy value, to make sure that no calls to sys_data_path() happen before the bootstrap is completed.

The CLI programs should still successfully bootstrap on the first call since they have should QCoreApplication initialised at this point.

**Comment by cme** [comment]
Filesystem::bootstrap couldn't be cleanly split after all, as some of the initialisation does need access to the application path via QApplication. So #936 is alternate solution which uses a dummy core app to bootstrap configuration before the GUI app starts.

**Pull request merged**
